import { trackRelationships } from "@/lib/learning-taxonomy";
import { enrichedTracks } from "@/lib/curriculum";

export interface TechnologyEntry {
  id: string;
  name: string;
  nameBn?: string;
  slug: string;
  category: string;
  subcategory: string;
  logo: string;
  coverImage?: string;
  description: string;
  descriptionBn?: string;
  history?: string;
  creator?: string;
  organization?: string;
  releaseDate?: string;
  currentVersion?: string;
  license?: string;
  officialWebsite?: string;
  githubRepo?: string;
  documentationUrl?: string;
  programmingLanguage?: string;
  type: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  ecosystem?: string;
  tags: string[];
  relatedTechnologies: string[];
  companiesUsing?: string[];
  jobMarketDemand?: string;
  learningCurve?: string;
  advantages: string[];
  disadvantages: string[];
  alternatives: string[];
  installationGuide?: string;
  basicExample?: string;
  advancedExample?: string;
  communityResources?: string[];
  youtubeResources?: string[];
  roadmap?: string[];
  careerPaths?: string[];
  bestPractices?: string[];
  securityConsiderations?: string[];
  performanceConsiderations?: string[];
  seoKeywords?: string[];
  relatedTrackId?: string;
  featured: boolean;
}

const BASE_TAGS: Record<string, string[]> = {
  frontend: ["web", "frontend", "ui", "browser"],
  backend: ["web", "backend", "server", "api"],
  database: ["data", "storage", "database", "persistence"],
  language: ["programming", "language"],
  framework: ["framework", "web"],
  tool: ["tool", "developer", "utility"],
};

function trackIcon(trackId: string): string {
  const track = enrichedTracks.find(t => t.id === trackId);
  return track?.icon ?? `https://img.icons8.com/color/96/${trackId}.png`;
}

function trackDescription(trackId: string): string {
  const rel = trackRelationships[trackId as keyof typeof trackRelationships];
  const track = enrichedTracks.find(t => t.id === trackId);
  if (!rel && !track) return "";
  const category = rel?.category ?? track?.category ?? "";
  const sub = rel?.subcategory ?? track?.subcategory ?? "";
  return `${track?.title ?? trackId} — ${category} / ${sub}. ${track?.tagline ?? ""}`;
}

export const technologies: Record<string, TechnologyEntry> = {};

const all: TechnologyEntry[] = [
  // ===== FRONTEND =====
  {
    id: "html", slug: "html", name: "HTML", nameBn: "এইচটিএমএল",
    category: "Frontend", subcategory: "Core Web",
    logo: trackIcon("html"), description: trackDescription("html"),
    type: "Markup Language", difficulty: "beginner",
    organization: "WHATWG / W3C", releaseDate: "1993", currentVersion: "HTML5",
    license: "Public Domain", officialWebsite: "https://html.spec.whatwg.org/",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/HTML",
    tags: [...BASE_TAGS.frontend, "markup", "web-standard"],
    relatedTechnologies: ["css", "javascript", "htmldom", "svg", "accessibility"],
    advantages: ["Easy to learn", "Universal browser support", "Semantic elements for SEO", "Works with all web technologies"],
    disadvantages: ["Limited styling by itself", "No logic or computation", "Requires CSS and JavaScript for modern sites"],
    alternatives: ["jsx", "pug", "markdown"],
    featured: true, relatedTrackId: "html", companiesUsing: ["Every website in the world"],
  },
  {
    id: "css", slug: "css", name: "CSS", nameBn: "সিএসএস",
    category: "Frontend", subcategory: "Core Web",
    logo: trackIcon("css"), description: trackDescription("css"),
    type: "Stylesheet Language", difficulty: "beginner",
    organization: "W3C", releaseDate: "1996", currentVersion: "CSS3",
    license: "Public Domain", officialWebsite: "https://www.w3.org/Style/CSS/",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    tags: [...BASE_TAGS.frontend, "styling", "design", "layout"],
    relatedTechnologies: ["html", "javascript", "sass", "tailwindcss", "bootstrap5"],
    advantages: ["Separates content from design", "Responsive design capabilities", "Rich animation support", "Wide browser support"],
    disadvantages: ["Global scope by default", "Can become hard to maintain at scale", "Lacks programming constructs"],
    alternatives: ["sass", "tailwindcss", "styled-components"],
    featured: true, relatedTrackId: "css",
  },
  {
    id: "javascript", slug: "javascript", name: "JavaScript", nameBn: "জাভাস্ক্রিপ্ট",
    category: "Frontend", subcategory: "Core Web",
    logo: trackIcon("javascript"), description: trackDescription("javascript"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "Ecma International", releaseDate: "1995", currentVersion: "ES2024",
    license: "MIT", officialWebsite: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    programmingLanguage: "JavaScript",
    tags: [...BASE_TAGS.frontend, "language", "dynamic", "event-driven"],
    relatedTechnologies: ["typescript", "nodejs", "react", "vue", "angular", "jquery"],
    advantages: ["Runs everywhere (browser, server, mobile)", "Huge ecosystem and community", "Flexible and dynamic", "Async programming with promises/async-await"],
    disadvantages: ["Dynamic typing can cause runtime errors", "Single-threaded (event loop)", "Callback hell (though promises help)", "Browser API inconsistencies"],
    alternatives: ["typescript", "python", "dart"],
    featured: true, relatedTrackId: "javascript",
  },
  {
    id: "typescript", slug: "typescript", name: "TypeScript", nameBn: "টাইপস্ক্রিপ্ট",
    category: "Frontend", subcategory: "Core Web",
    logo: trackIcon("typescript"), description: trackDescription("typescript"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "Microsoft", releaseDate: "2012", currentVersion: "5.7",
    license: "Apache 2.0", officialWebsite: "https://www.typescriptlang.org/",
    documentationUrl: "https://www.typescriptlang.org/docs/",
    programmingLanguage: "TypeScript",
    tags: [...BASE_TAGS.frontend, "language", "static-typing", "compiler"],
    relatedTechnologies: ["javascript", "react", "angular", "nodejs"],
    advantages: ["Static type checking", "Better IDE support and autocompletion", "Catches bugs at compile time", "Great for large codebases"],
    disadvantages: ["Extra compilation step", "Learning curve for types system", "Type definitions needed for some libraries", "Can slow down development for small projects"],
    alternatives: ["flow", "javascript", "rescript"],
    featured: true, relatedTrackId: "typescript",
  },
  {
    id: "htmldom", slug: "htmldom", name: "HTML DOM", nameBn: "এইচটিএমএল ডম",
    category: "Frontend", subcategory: "Browser APIs",
    logo: trackIcon("htmldom"), description: trackDescription("htmldom"),
    type: "Browser API", difficulty: "intermediate",
    organization: "W3C / WHATWG", releaseDate: "1998",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model",
    tags: [...BASE_TAGS.frontend, "dom", "api", "browser"],
    relatedTechnologies: ["javascript", "html", "ajax", "jquery"],
    advantages: ["Direct manipulation of page content", "Event-driven architecture", "W3C standard, supported everywhere"],
    disadvantages: ["Can be verbose without frameworks", "Direct manipulation can be slow", "No built-in state management"],
    alternatives: ["react", "vue", "jquery"],
    featured: false, relatedTrackId: "htmldom",
  },
  {
    id: "ajax", slug: "ajax", name: "AJAX", nameBn: "এজাক্স",
    category: "Frontend", subcategory: "Browser APIs",
    logo: trackIcon("ajax"), description: trackDescription("ajax"),
    type: "Web Development Technique", difficulty: "intermediate",
    releaseDate: "1999",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX",
    tags: [...BASE_TAGS.frontend, "api", "async", "networking"],
    relatedTechnologies: ["javascript", "json", "xml", "nodejs"],
    advantages: ["Asynchronous data loading", "No page reloads needed", "Better user experience"],
    disadvantages: ["SEO challenges for dynamic content", "Cross-origin restrictions", "Adds complexity"],
    alternatives: ["fetch", "axios", "graphql"],
    featured: true, relatedTrackId: "ajax",
  },
  {
    id: "rwd", slug: "responsive-web-design", name: "Responsive Web Design", nameBn: "রেসপন্সিভ ওয়েব ডিজাইন",
    category: "Frontend", subcategory: "Core Web",
    logo: trackIcon("rwd"), description: trackDescription("rwd"),
    type: "Design Approach", difficulty: "intermediate",
    tags: [...BASE_TAGS.frontend, "responsive", "design", "mobile"],
    relatedTechnologies: ["css", "html", "bootstrap5", "tailwindcss"],
    advantages: ["Works on all devices", "Better SEO", "Single codebase for all screen sizes"],
    disadvantages: ["Can be complex to implement", "Performance considerations", "Design compromises needed"],
    alternatives: ["adaptive-design", "mobile-first", "progressive-web-apps"],
    featured: true, relatedTrackId: "rwd",
  },
  {
    id: "svg", slug: "svg", name: "SVG", nameBn: "এসভিজি",
    category: "Frontend", subcategory: "Graphics & Visuals",
    logo: trackIcon("svg"), description: trackDescription("svg"),
    type: "Vector Image Format", difficulty: "intermediate",
    organization: "W3C", releaseDate: "2001",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/SVG",
    tags: [...BASE_TAGS.frontend, "vector", "graphics", "animation"],
    relatedTechnologies: ["canvas", "html", "css", "icons"],
    advantages: ["Resolution independent", "Small file sizes", "Animatable and scriptable", "Accessible"],
    disadvantages: ["Complex shapes are hard to code manually", "Limited for photorealistic images", "Browser inconsistencies"],
    alternatives: ["canvas", "png", "webp"],
    featured: true, relatedTrackId: "svg",
  },
  {
    id: "canvas", slug: "canvas", name: "Canvas", nameBn: "ক্যানভাস",
    category: "Frontend", subcategory: "Graphics & Visuals",
    logo: trackIcon("canvas"), description: trackDescription("canvas"),
    type: "Browser API", difficulty: "intermediate",
    organization: "WHATWG", releaseDate: "2004",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API",
    tags: [...BASE_TAGS.frontend, "graphics", "2d", "rendering", "game"],
    relatedTechnologies: ["svg", "javascript", "html"],
    advantages: ["Pixel-level control", "High performance for games/graphics", "Works with WebGL for 3D"],
    disadvantages: ["No DOM events on drawn elements", "No built-in animation support", "Requires manual redraw"],
    alternatives: ["svg", "webgl", "pixi-js"],
    featured: true, relatedTrackId: "canvas",
  },
  {
    id: "accessibility", slug: "accessibility", name: "Accessibility", nameBn: "অ্যাক্সেসিবিলিটি",
    category: "Frontend", subcategory: "Web Standards",
    logo: trackIcon("accessibility"), description: trackDescription("accessibility"),
    type: "Web Standard", difficulty: "intermediate",
    organization: "W3C / WAI", releaseDate: "1999",
    officialWebsite: "https://www.w3.org/WAI/",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/Accessibility",
    tags: [...BASE_TAGS.frontend, "a11y", "inclusive", "wai-aria", "standard"],
    relatedTechnologies: ["html", "css", "javascript", "rwd"],
    advantages: ["Inclusive design for all users", "Better SEO", "Legal compliance", "Better UX for everyone"],
    disadvantages: ["Requires extra development effort", "Testing can be time-consuming", "Ongoing maintenance"],
    alternatives: [],
    featured: true, relatedTrackId: "accessibility",
  },
  {
    id: "icons", slug: "icons", name: "Icons", nameBn: "আইকন",
    category: "Frontend", subcategory: "Graphics & Visuals",
    logo: trackIcon("icons"), description: trackDescription("icons"),
    type: "Design Element", difficulty: "beginner",
    tags: [...BASE_TAGS.frontend, "design", "ui", "iconography"],
    relatedTechnologies: ["svg", "html", "css", "colors"],
    advantages: ["Improves visual communication", "Small file sizes with SVG", "Easily customizable"],
    disadvantages: ["Can be overused", "Accessibility concerns if not labeled", "Consistency across icon sets"],
    alternatives: ["emoji", "ascii-art"],
    featured: false, relatedTrackId: "icons",
  },
  {
    id: "colors", slug: "web-colors", name: "Web Colors", nameBn: "ওয়েব কালার",
    category: "Frontend", subcategory: "Web Standards",
    logo: trackIcon("colors"), description: trackDescription("colors"),
    type: "Web Standard", difficulty: "beginner",
    tags: [...BASE_TAGS.frontend, "design", "color", "css"],
    relatedTechnologies: ["css", "html", "icons", "emojis"],
    advantages: ["Enables beautiful designs", "Accessibility contrast requirements", "Brand identity"],
    disadvantages: ["Color blindness considerations", "Cross-device calibration issues"],
    alternatives: [],
    featured: false, relatedTrackId: "colors",
  },
  {
    id: "emojis", slug: "emojis-unicode", name: "Emojis & Unicode", nameBn: "ইমোজি ও ইউনিকোড",
    category: "Frontend", subcategory: "Web Standards",
    logo: trackIcon("emojis"), description: trackDescription("emojis"),
    type: "Text Encoding Standard", difficulty: "beginner",
    organization: "Unicode Consortium", releaseDate: "1991",
    officialWebsite: "https://home.unicode.org/",
    tags: ["text", "encoding", "unicode", "character"],
    relatedTechnologies: ["html", "css", "javascript", "colors"],
    advantages: ["Universal character representation", "Emoji support across platforms", "Multi-language support"],
    disadvantages: ["Some emoji render differently per platform", "Large memory footprint for some scripts"],
    alternatives: ["ascii"],
    featured: false, relatedTrackId: "emojis",
  },
  {
    id: "unicode_utf8", slug: "utf8-encoding", name: "UTF-8 & Character Encoding", nameBn: "ইউটিএফ-৮ ও ক্যারেক্টার এনকোডিং",
    category: "Frontend", subcategory: "Web Standards",
    logo: trackIcon("unicode_utf8"), description: trackDescription("unicode_utf8"),
    type: "Character Encoding", difficulty: "intermediate",
    organization: "Unicode Consortium / RFC 3629", releaseDate: "1993",
    officialWebsite: "https://www.unicode.org/",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Glossary/UTF-8",
    tags: ["text", "encoding", "unicode", "utf8", "character-set"],
    relatedTechnologies: ["emojis", "html", "javascript", "xml", "json"],
    advantages: ["Backward compatible with ASCII", "Efficient for Latin scripts", "Variable-width encoding saves space"],
    disadvantages: ["Multi-byte sequences can be tricky", "Not self-synchronizing", "Byte order not explicit"],
    alternatives: ["utf-16", "utf-32", "iso-8859-1"],
    featured: false, relatedTrackId: "unicode_utf8",
  },
  {
    id: "intro-html-css", slug: "intro-html-css", name: "Intro to HTML & CSS", nameBn: "এইচটিএমএল ও সিএসএস পরিচিতি",
    category: "Frontend", subcategory: "Core Web",
    logo: trackIcon("intro-html-css"), description: trackDescription("intro-html-css"),
    type: "Learning Track", difficulty: "beginner",
    tags: [...BASE_TAGS.frontend, "beginner", "tutorial"],
    relatedTechnologies: ["html", "css", "rwd"],
    advantages: [], disadvantages: [], alternatives: [],
    featured: false, relatedTrackId: "intro-html-css",
  },
  // ===== FRONTEND FRAMEWORKS =====
  {
    id: "react", slug: "react", name: "React", nameBn: "রিঅ্যাক্ট",
    category: "Frontend", subcategory: "Frontend Frameworks",
    logo: trackIcon("react"), description: trackDescription("react"),
    type: "UI Library", difficulty: "intermediate",
    organization: "Meta (Facebook)", releaseDate: "2013", currentVersion: "19",
    license: "MIT", officialWebsite: "https://react.dev/",
    githubRepo: "https://github.com/facebook/react",
    documentationUrl: "https://react.dev/learn",
    programmingLanguage: "JavaScript / TypeScript",
    tags: [...BASE_TAGS.frontend, "ui-library", "component-based", "spa", "virtual-dom"],
    relatedTechnologies: ["typescript", "nextjs", "nodejs", "redux", "tailwindcss"],
    companiesUsing: ["Meta", "Netflix", "Airbnb", "Uber", "Twitter/X", "Shopify", "Discord"],
    jobMarketDemand: "Very High — one of the most demanded frontend skills worldwide",
    learningCurve: "Moderate — JSX and component model take time to master",
    advantages: ["Virtual DOM for performance", "Huge ecosystem and community", "Component reusability", "Great developer tools", "Strong TypeScript support"],
    disadvantages: ["Fast-changing ecosystem", "JSX can be unfamiliar", "Boilerplate for complex state management", "SEO requires SSR (Next.js)"],
    alternatives: ["vue", "angular", "svelte", "solid"],
    securityConsiderations: ["Use proper input sanitization", "Avoid dangerouslySetInnerHTML", "Keep dependencies updated"],
    performanceConsiderations: ["Use React.memo for expensive renders", "Code-split with lazy/Suspense", "Minimize re-renders with useMemo/useCallback"],
    featured: true, relatedTrackId: "react",
  },
  {
    id: "vue", slug: "vue", name: "Vue.js", nameBn: "ভিউ.জেএস",
    category: "Frontend", subcategory: "Frontend Frameworks",
    logo: trackIcon("vue"), description: trackDescription("vue"),
    type: "Frontend Framework", difficulty: "intermediate",
    organization: "Evan You", releaseDate: "2014", currentVersion: "3.5",
    license: "MIT", officialWebsite: "https://vuejs.org/",
    githubRepo: "https://github.com/vuejs/core",
    documentationUrl: "https://vuejs.org/guide/introduction.html",
    programmingLanguage: "JavaScript / TypeScript",
    tags: [...BASE_TAGS.frontend, "framework", "reactive", "spa"],
    relatedTechnologies: ["typescript", "react", "angular", "nuxtjs"],
    advantages: ["Gentle learning curve", "Excellent documentation", "Reactive and composable", "Flexible and scalable"],
    disadvantages: ["Smaller ecosystem than React", "Less job demand than React", "Breaking changes from v2 to v3"],
    alternatives: ["react", "angular", "svelte"],
    featured: true, relatedTrackId: "vue",
  },
  {
    id: "angular", slug: "angular", name: "Angular", nameBn: "অ্যাঙ্গুলার",
    category: "Frontend", subcategory: "Frontend Frameworks",
    logo: trackIcon("angular"), description: trackDescription("angular"),
    type: "Frontend Framework", difficulty: "advanced",
    organization: "Google", releaseDate: "2016", currentVersion: "19",
    license: "MIT", officialWebsite: "https://angular.dev/",
    githubRepo: "https://github.com/angular/angular",
    documentationUrl: "https://angular.dev/overview",
    programmingLanguage: "TypeScript",
    tags: [...BASE_TAGS.frontend, "framework", "spa", "typescript", "enterprise"],
    relatedTechnologies: ["typescript", "react", "vue", "rxjs"],
    advantages: ["Full-featured framework included", "TypeScript built-in", "Powerful CLI", "Great for enterprise apps"],
    disadvantages: ["Steep learning curve", "Opinionated structure", "Heavier bundle size", "Less flexible than React"],
    alternatives: ["react", "vue", "svelte"],
    featured: true, relatedTrackId: "angular",
  },
  {
    id: "jquery", slug: "jquery", name: "jQuery", nameBn: "জেকোয়েরি",
    category: "Frontend", subcategory: "Frontend Frameworks",
    logo: trackIcon("jquery"), description: trackDescription("jquery"),
    type: "JavaScript Library", difficulty: "intermediate",
    organization: "JS Foundation", releaseDate: "2006", currentVersion: "3.7",
    license: "MIT", officialWebsite: "https://jquery.com/",
    githubRepo: "https://github.com/jquery/jquery",
    documentationUrl: "https://api.jquery.com/",
    programmingLanguage: "JavaScript",
    tags: [...BASE_TAGS.frontend, "library", "dom-manipulation", "legacy"],
    relatedTechnologies: ["javascript", "htmldom", "ajax"],
    advantages: ["Simplifies DOM manipulation", "Cross-browser compatibility", "Rich plugin ecosystem", "Chainable API"],
    disadvantages: ["Less relevant in modern web dev", "Can lead to messy code", "Performance overhead", "No longer needed with modern APIs"],
    alternatives: ["javascript", "react", "alpinejs"],
    featured: false, relatedTrackId: "jquery",
  },
  // ===== CSS FRAMEWORKS =====
  {
    id: "bootstrap5", slug: "bootstrap", name: "Bootstrap", nameBn: "বুটস্ট্র্যাপ",
    category: "Frontend", subcategory: "UI Frameworks",
    logo: trackIcon("bootstrap5"), description: trackDescription("bootstrap5"),
    type: "CSS Framework", difficulty: "beginner",
    organization: "Twitter / Bootstrap Team", releaseDate: "2011", currentVersion: "5.3",
    license: "MIT", officialWebsite: "https://getbootstrap.com/",
    githubRepo: "https://github.com/twbs/bootstrap",
    documentationUrl: "https://getbootstrap.com/docs/5.3/getting-started/introduction/",
    tags: [...BASE_TAGS.frontend, "css-framework", "responsive", "ui-kit"],
    relatedTechnologies: ["css", "html", "javascript", "sass"],
    advantages: ["Quick prototyping", "Responsive grid system", "Large component library", "Extensive browser compatibility"],
    disadvantages: ["Sites can look similar", "Large bundle size", "Overriding styles can be tricky"],
    alternatives: ["tailwindcss", "foundation", "bulma"],
    featured: true, relatedTrackId: "bootstrap5",
  },
  {
    id: "tailwindcss", slug: "tailwind-css", name: "Tailwind CSS", nameBn: "টেইলউইন্ড সিএসএস",
    category: "Frontend", subcategory: "UI Frameworks",
    logo: "https://img.icons8.com/color/96/tailwindcss.png",
    description: "A utility-first CSS framework for rapidly building custom designs without leaving your HTML.",
    type: "CSS Framework", difficulty: "intermediate",
    organization: "Tailwind Labs", releaseDate: "2017", currentVersion: "3.4",
    license: "MIT", officialWebsite: "https://tailwindcss.com/",
    githubRepo: "https://github.com/tailwindlabs/tailwindcss",
    documentationUrl: "https://tailwindcss.com/docs",
    tags: [...BASE_TAGS.frontend, "css-framework", "utility-first", "design-system"],
    relatedTechnologies: ["css", "react", "vue", "postcss"],
    advantages: ["Highly customizable", "Small production bundle with purging", "No naming conventions needed", "Rapid prototyping"],
    disadvantages: ["HTML can look messy", "Learning curve for utility classes", "Requires build step"],
    alternatives: ["bootstrap5", "styled-components", "sass"],
    featured: true,
  },
  {
    id: "w3css", slug: "w3css", name: "W3.CSS", nameBn: "ডব্লিউথ্রি.সিএসএস",
    category: "Frontend", subcategory: "UI Frameworks",
    logo: trackIcon("w3css"), description: trackDescription("w3css"),
    type: "CSS Framework", difficulty: "beginner",
    organization: "W3Schools", releaseDate: "2015", currentVersion: "4.15",
    license: "MIT", officialWebsite: "https://www.w3schools.com/w3css/",
    tags: [...BASE_TAGS.frontend, "css-framework", "beginner-friendly"],
    relatedTechnologies: ["css", "html"],
    advantages: ["Very easy to learn", "No dependencies", "Lightweight"],
    disadvantages: ["Limited features", "Less modern than Bootstrap/Tailwind", "Smaller community"],
    alternatives: ["bootstrap5", "tailwindcss"],
    featured: false, relatedTrackId: "w3css",
  },
  {
    id: "bootstrap3", slug: "bootstrap3", name: "Bootstrap 3", nameBn: "বুটস্ট্র্যাপ ৩",
    category: "Frontend", subcategory: "UI Frameworks",
    logo: trackIcon("bootstrap3"), description: trackDescription("bootstrap3"),
    type: "CSS Framework", difficulty: "beginner",
    releaseDate: "2013",
    tags: [...BASE_TAGS.frontend, "css-framework", "legacy"],
    relatedTechnologies: ["bootstrap4", "bootstrap5", "css", "html"],
    advantages: [], disadvantages: [], alternatives: ["bootstrap5", "tailwindcss"],
    featured: false, relatedTrackId: "bootstrap3",
  },
  {
    id: "bootstrap4", slug: "bootstrap4", name: "Bootstrap 4", nameBn: "বুটস্ট্র্যাপ ৪",
    category: "Frontend", subcategory: "UI Frameworks",
    logo: trackIcon("bootstrap4"), description: trackDescription("bootstrap4"),
    type: "CSS Framework", difficulty: "beginner",
    releaseDate: "2018",
    tags: [...BASE_TAGS.frontend, "css-framework", "responsive"],
    relatedTechnologies: ["bootstrap3", "bootstrap5", "css", "jquery"],
    advantages: [], disadvantages: [], alternatives: ["bootstrap5", "tailwindcss"],
    featured: false, relatedTrackId: "bootstrap4",
  },
  // ===== BACKEND =====
  {
    id: "nodejs", slug: "nodejs", name: "Node.js", nameBn: "নোড.জেএস",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("nodejs"), description: trackDescription("nodejs"),
    type: "JavaScript Runtime", difficulty: "intermediate",
    organization: "OpenJS Foundation", releaseDate: "2009", currentVersion: "22",
    license: "MIT", officialWebsite: "https://nodejs.org/",
    githubRepo: "https://github.com/nodejs/node",
    documentationUrl: "https://nodejs.org/docs/latest/api/",
    programmingLanguage: "JavaScript",
    tags: [...BASE_TAGS.backend, "runtime", "event-driven", "non-blocking"],
    relatedTechnologies: ["javascript", "typescript", "expressjs", "mongodb", "npm"],
    companiesUsing: ["Netflix", "PayPal", "Uber", "LinkedIn", "Medium", "Trello"],
    jobMarketDemand: "High — essential for fullstack JavaScript developers",
    advantages: ["JavaScript everywhere", "Non-blocking I/O", "Huge npm ecosystem", "Fast execution (V8 engine)"],
    disadvantages: ["Single-threaded (not ideal for CPU-heavy)", "Callback patterns can be complex", "NPM package quality varies"],
    alternatives: ["deno", "bun", "python", "go"],
    featured: true, relatedTrackId: "nodejs",
  },
  {
    id: "php", slug: "php", name: "PHP", nameBn: "পিএইচপি",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("php"), description: trackDescription("php"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "PHP Group", releaseDate: "1995", currentVersion: "8.4",
    license: "PHP License", officialWebsite: "https://www.php.net/",
    documentationUrl: "https://www.php.net/docs.php",
    programmingLanguage: "PHP",
    tags: [...BASE_TAGS.backend, "language", "server-side", "scripting"],
    relatedTechnologies: ["mysql", "laravel", "wordpress", "html"],
    companiesUsing: ["Wikipedia", "WordPress", "Slack", "Etsy"],
    advantages: ["Easy to learn", "Runs on almost all servers", "Huge CMS ecosystem (WordPress)", "Built-in database support"],
    disadvantages: ["Inconsistent language design", "Security pitfalls", "Not ideal for real-time apps"],
    alternatives: ["nodejs", "python", "go", "java"],
    featured: true, relatedTrackId: "php",
  },
  {
    id: "python", slug: "python", name: "Python", nameBn: "পাইথন",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("python"), description: trackDescription("python"),
    type: "Programming Language", difficulty: "beginner",
    organization: "Python Software Foundation", releaseDate: "1991", currentVersion: "3.13",
    license: "PSF License", officialWebsite: "https://www.python.org/",
    documentationUrl: "https://docs.python.org/3/",
    programmingLanguage: "Python",
    tags: [...BASE_TAGS.backend, "language", "general-purpose", "scripting", "ai"],
    relatedTechnologies: ["django", "numpy", "pandas", "machinelearning", "ai"],
    companiesUsing: ["Google", "Netflix", "Spotify", "Instagram", "Dropbox"],
    jobMarketDemand: "Very High — top language for AI/ML, data science, and backend",
    advantages: ["Extremely readable syntax", "Huge standard library", "Excellent for AI/ML and data science", "Large community"],
    disadvantages: ["Slower than compiled languages", "GIL limits threading", "Not ideal for mobile development"],
    alternatives: ["javascript", "go", "rust", "java"],
    featured: true, relatedTrackId: "python",
  },
  {
    id: "django", slug: "django", name: "Django", nameBn: "জ্যাঙ্গো",
    category: "Backend", subcategory: "Backend Frameworks",
    logo: trackIcon("django"), description: trackDescription("django"),
    type: "Web Framework", difficulty: "intermediate",
    organization: "Django Software Foundation", releaseDate: "2005", currentVersion: "5.2",
    license: "BSD", officialWebsite: "https://www.djangoproject.com/",
    githubRepo: "https://github.com/django/django",
    documentationUrl: "https://docs.djangoproject.com/",
    programmingLanguage: "Python",
    tags: [...BASE_TAGS.backend, "framework", "batteries-included", "python"],
    relatedTechnologies: ["python", "postgresql", "sql", "rest-api"],
    advantages: ["Batteries-included approach", "Admin interface built-in", "ORM for database operations", "Great security features"],
    disadvantages: ["Monolithic by default", "Can be heavy for simple apps", "ORM can be slow for complex queries"],
    alternatives: ["flask", "fastapi", "expressjs", "laravel"],
    featured: true, relatedTrackId: "django",
  },
  {
    id: "asp", slug: "aspnet", name: "ASP.NET", nameBn: "এএসপি.নেট",
    category: "Backend", subcategory: "Enterprise Development",
    logo: trackIcon("asp"), description: trackDescription("asp"),
    type: "Web Framework", difficulty: "advanced",
    organization: "Microsoft", releaseDate: "2002", currentVersion: "9.0",
    license: "MIT", officialWebsite: "https://dotnet.microsoft.com/apps/aspnet",
    documentationUrl: "https://learn.microsoft.com/aspnet/core/",
    programmingLanguage: "C#",
    tags: [...BASE_TAGS.backend, "framework", "enterprise", "microsoft"],
    relatedTechnologies: ["csharp", "sql", "azure"],
    advantages: ["High performance", "Strong typing with C#", "Excellent tooling", "Enterprise-grade"],
    disadvantages: ["Windows-centric historically", "Heavier framework", "Learning curve"],
    alternatives: ["django", "spring-boot", "expressjs", "laravel"],
    featured: true, relatedTrackId: "asp",
  },
  {
    id: "go", slug: "go", name: "Go", nameBn: "গো",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("go"), description: trackDescription("go"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "Google", releaseDate: "2009", currentVersion: "1.23",
    license: "BSD", officialWebsite: "https://go.dev/",
    githubRepo: "https://github.com/golang/go",
    documentationUrl: "https://go.dev/doc/",
    programmingLanguage: "Go",
    tags: [...BASE_TAGS.backend, "language", "concurrent", "compiled", "systems"],
    relatedTechnologies: ["c", "cpp", "docker", "kubernetes", "aws"],
    advantages: ["Great concurrency support", "Fast compilation", "Simple and readable", "Excellent standard library"],
    disadvantages: ["No generics (historically)", "Smaller ecosystem than Java/Python", "Verbose error handling"],
    alternatives: ["rust", "java", "python", "nodejs"],
    featured: true, relatedTrackId: "go",
  },
  {
    id: "java", slug: "java", name: "Java", nameBn: "জাভা",
    category: "Backend", subcategory: "Enterprise Development",
    logo: trackIcon("java"), description: trackDescription("java"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "Oracle Corporation", releaseDate: "1995", currentVersion: "21",
    license: "GPL + Classpath Exception", officialWebsite: "https://www.oracle.com/java/",
    documentationUrl: "https://docs.oracle.com/en/java/",
    programmingLanguage: "Java",
    tags: [...BASE_TAGS.backend, "language", "enterprise", "jvm", "object-oriented"],
    relatedTechnologies: ["kotlin", "spring-boot", "sql", "android"],
    companiesUsing: ["Amazon", "Google", "Netflix", "Spotify", "Twitter/X"],
    advantages: ["Write once, run anywhere", "Mature ecosystem", "Excellent tooling", "Enterprise-proven"],
    disadvantages: ["Verbose syntax", "Memory consumption", "Slow startup time"],
    alternatives: ["kotlin", "csharp", "go", "python"],
    featured: true, relatedTrackId: "java",
  },
  {
    id: "kotlin", slug: "kotlin", name: "Kotlin", nameBn: "কোটলিন",
    category: "Backend", subcategory: "Enterprise Development",
    logo: trackIcon("kotlin"), description: trackDescription("kotlin"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "JetBrains", releaseDate: "2011", currentVersion: "2.1",
    license: "Apache 2.0", officialWebsite: "https://kotlinlang.org/",
    githubRepo: "https://github.com/JetBrains/kotlin",
    documentationUrl: "https://kotlinlang.org/docs/home.html",
    programmingLanguage: "Kotlin",
    tags: [...BASE_TAGS.backend, "language", "jvm", "modern", "android"],
    relatedTechnologies: ["java", "android", "spring-boot"],
    advantages: ["Concise syntax", "Fully interoperable with Java", "Null safety built-in", "Modern language features"],
    disadvantages: ["Smaller ecosystem than Java", "Slower compilation than Java", "Fewer resources available"],
    alternatives: ["java", "swift", "go"],
    featured: true, relatedTrackId: "kotlin",
  },
  {
    id: "csharp", slug: "csharp", name: "C#", nameBn: "সি#",
    category: "Backend", subcategory: "Enterprise Development",
    logo: trackIcon("csharp"), description: trackDescription("csharp"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "Microsoft", releaseDate: "2000", currentVersion: "13",
    license: "MIT", officialWebsite: "https://learn.microsoft.com/dotnet/csharp/",
    documentationUrl: "https://learn.microsoft.com/dotnet/csharp/",
    programmingLanguage: "C#",
    tags: [...BASE_TAGS.backend, "language", "enterprise", "microsoft", "object-oriented"],
    relatedTechnologies: ["asp", "sql", "dotnet", "azure"],
    advantages: ["Elegant language design", "Great .NET ecosystem", "Cross-platform with .NET Core", "Strong typing and performance"],
    disadvantages: ["Historically Windows-focused", "Fewer third-party libraries than Java/JS"],
    alternatives: ["java", "go", "kotlin"],
    featured: true, relatedTrackId: "csharp",
  },
  {
    id: "c", slug: "c", name: "C Programming", nameBn: "সি প্রোগ্রামিং",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("c"), description: trackDescription("c"),
    type: "Programming Language", difficulty: "beginner",
    organization: "ANSI / ISO", releaseDate: "1972", currentVersion: "C17 / C23",
    license: "Public Domain", officialWebsite: "https://en.cppreference.com/w/c",
    documentationUrl: "https://en.cppreference.com/w/c",
    programmingLanguage: "C",
    tags: ["programming", "language", "systems", "compiled", "procedural"],
    relatedTechnologies: ["cpp", "rust", "unix", "linux", "raspberry_pi"],
    advantages: ["Extremely fast and efficient", "Direct hardware access", "Foundation of most modern languages", "Portable"],
    disadvantages: ["Manual memory management", "No object-oriented features", "Low-level can be error-prone"],
    alternatives: ["cpp", "rust", "go", "zig"],
    featured: true, relatedTrackId: "c",
  },
  {
    id: "cpp", slug: "cpp", name: "C++", nameBn: "সি++",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("cpp"), description: trackDescription("cpp"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "ISO/IEC", releaseDate: "1985", currentVersion: "C++20 / C++23",
    license: "Public Domain", officialWebsite: "https://isocpp.org/",
    documentationUrl: "https://en.cppreference.com/w/cpp",
    programmingLanguage: "C++",
    tags: ["programming", "language", "systems", "compiled", "object-oriented"],
    relatedTechnologies: ["c", "rust", "java", "unreal-engine"],
    advantages: ["High performance", "Fine-grained control over resources", "Object-oriented + procedural", "Large codebase compatibility"],
    disadvantages: ["Complex syntax", "Long compile times", "Memory safety issues", "Steep learning curve"],
    alternatives: ["rust", "go", "java", "c"],
    featured: true, relatedTrackId: "cpp",
  },
  {
    id: "rust", slug: "rust", name: "Rust", nameBn: "রাস্ট",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("rust"), description: trackDescription("rust"),
    type: "Programming Language", difficulty: "advanced",
    organization: "Mozilla / Rust Foundation", releaseDate: "2015", currentVersion: "1.83",
    license: "MIT / Apache 2.0", officialWebsite: "https://www.rust-lang.org/",
    githubRepo: "https://github.com/rust-lang/rust",
    documentationUrl: "https://doc.rust-lang.org/book/",
    programmingLanguage: "Rust",
    tags: ["programming", "language", "systems", "safe", "concurrent"],
    relatedTechnologies: ["c", "cpp", "go", "webassembly"],
    advantages: ["Memory safety without GC", "Excellent concurrency", "Zero-cost abstractions", "Growing ecosystem"],
    disadvantages: ["Steep learning curve (borrow checker)", "Longer development time", "Smaller ecosystem than C/C++"],
    alternatives: ["c", "cpp", "go", "zig"],
    featured: true, relatedTrackId: "rust",
  },
  {
    id: "swift", slug: "swift", name: "Swift", nameBn: "সুইফট",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("swift"), description: trackDescription("swift"),
    type: "Programming Language", difficulty: "beginner",
    organization: "Apple", releaseDate: "2014", currentVersion: "6.0",
    license: "Apache 2.0", officialWebsite: "https://www.swift.org/",
    githubRepo: "https://github.com/apple/swift",
    documentationUrl: "https://docs.swift.org/swift-book/",
    programmingLanguage: "Swift",
    tags: ["programming", "language", "apple", "mobile", "ios"],
    relatedTechnologies: ["kotlin", "c", "cpp", "objective-c"],
    advantages: ["Modern and expressive syntax", "Excellent performance", "Safe by design", "Open source"],
    disadvantages: ["Primarily Apple ecosystem", "Smaller community than other languages", "Less cross-platform support"],
    alternatives: ["kotlin", "rust", "go"],
    featured: true, relatedTrackId: "swift",
  },
  {
    id: "r", slug: "r", name: "R", nameBn: "আর",
    category: "Backend", subcategory: "Server Languages",
    logo: trackIcon("r"), description: trackDescription("r"),
    type: "Programming Language", difficulty: "intermediate",
    organization: "R Foundation", releaseDate: "1995", currentVersion: "4.4",
    license: "GPL-2", officialWebsite: "https://www.r-project.org/",
    documentationUrl: "https://cran.r-project.org/manuals.html",
    programmingLanguage: "R",
    tags: ["programming", "language", "statistics", "data-science"],
    relatedTechnologies: ["statistic", "python", "numpy", "pandas", "matplotlib"],
    advantages: ["Designed for data analysis", "Excellent visualization", "Strong statistical packages", "Great for academic research"],
    disadvantages: ["Slower than Python for general tasks", "Steeper learning curve", "Memory inefficient"],
    alternatives: ["python", "julia", "matlab"],
    featured: true, relatedTrackId: "r",
  },
  // ===== DATABASES =====
  {
    id: "sql", slug: "sql", name: "SQL", nameBn: "এসকিউএল",
    category: "Databases", subcategory: "Query Languages",
    logo: trackIcon("sql"), description: trackDescription("sql"),
    type: "Query Language", difficulty: "beginner",
    organization: "ISO/IEC", releaseDate: "1974",
    documentationUrl: "https://www.w3schools.com/sql/",
    tags: [...BASE_TAGS.database, "query-language", "relational"],
    relatedTechnologies: ["mysql", "postgresql", "sqlite"],
    advantages: ["Universal database language", "Declarative query style", "Strong data integrity"],
    disadvantages: ["Limited for hierarchical data", "Can be slow with deep joins", "Not ideal for real-time streaming"],
    alternatives: ["mongodb", "graphql", "nosql"],
    featured: true, relatedTrackId: "sql",
  },
  {
    id: "mysql", slug: "mysql", name: "MySQL", nameBn: "মাইএসকিউএল",
    category: "Databases", subcategory: "Relational Databases",
    logo: trackIcon("mysql"), description: trackDescription("mysql"),
    type: "Database Management System", difficulty: "intermediate",
    organization: "Oracle Corporation", releaseDate: "1995", currentVersion: "9.0",
    license: "GPL / Commercial", officialWebsite: "https://www.mysql.com/",
    documentationUrl: "https://dev.mysql.com/doc/",
    tags: [...BASE_TAGS.database, "relational", "rdbms", "sql"],
    relatedTechnologies: ["sql", "php", "postgresql", "mariadb"],
    advantages: ["Very popular and widely used", "Great performance", "Acid compliant", "Good tooling"],
    disadvantages: ["Some features are enterprise-only", "Less feature-rich than PostgreSQL", "Oracle ownership concerns"],
    alternatives: ["postgresql", "sqlite", "mariadb"],
    featured: true, relatedTrackId: "mysql",
  },
  {
    id: "postgresql", slug: "postgresql", name: "PostgreSQL", nameBn: "পোস্টগ্রেএসকিউএল",
    category: "Databases", subcategory: "Relational Databases",
    logo: trackIcon("postgresql"), description: trackDescription("postgresql"),
    type: "Database Management System", difficulty: "intermediate",
    organization: "PostgreSQL Global Development Group", releaseDate: "1996", currentVersion: "17",
    license: "PostgreSQL License", officialWebsite: "https://www.postgresql.org/",
    githubRepo: "https://github.com/postgres/postgres",
    documentationUrl: "https://www.postgresql.org/docs/",
    tags: [...BASE_TAGS.database, "relational", "rdbms", "advanced", "open-source"],
    relatedTechnologies: ["sql", "nodejs", "django", "python"],
    advantages: ["Advanced SQL features", "Excellent extension system", "Strong ACID compliance", "Great for complex queries"],
    disadvantages: ["Lower write performance than MySQL", "Configuration can be complex", "Fewer managed hosting options"],
    alternatives: ["mysql", "mongodb", "sqlite"],
    featured: true, relatedTrackId: "postgresql",
  },
  {
    id: "mongodb", slug: "mongodb", name: "MongoDB", nameBn: "মঙ্গোডিবি",
    category: "Databases", subcategory: "NoSQL Databases",
    logo: trackIcon("mongodb"), description: trackDescription("mongodb"),
    type: "Database Management System", difficulty: "intermediate",
    organization: "MongoDB Inc.", releaseDate: "2009", currentVersion: "8.0",
    license: "Server Side Public License", officialWebsite: "https://www.mongodb.com/",
    githubRepo: "https://github.com/mongodb/mongo",
    documentationUrl: "https://www.mongodb.com/docs/",
    tags: [...BASE_TAGS.database, "nosql", "document", "json"],
    relatedTechnologies: ["json", "nodejs", "sql", "expressjs"],
    advantages: ["Flexible document model", "Horizontal scaling built-in", "Great for JSON data", "Developer-friendly"],
    disadvantages: ["No joins (by design)", "Less mature transactions", "Memory consuming"],
    alternatives: ["postgresql", "firebase", "redis", "cassandra"],
    featured: true, relatedTrackId: "mongodb",
  },
  {
    id: "json", slug: "json", name: "JSON", nameBn: "জেসন",
    category: "Databases", subcategory: "Data Formats",
    logo: trackIcon("json"), description: trackDescription("json"),
    type: "Data Interchange Format", difficulty: "beginner",
    organization: "ECMA / IETF", releaseDate: "2001", currentVersion: "ECMA-404",
    license: "Public Domain", officialWebsite: "https://www.json.org/",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/JSON",
    tags: [...BASE_TAGS.database, "format", "serialization", "lightweight"],
    relatedTechnologies: ["javascript", "xml", "mongodb", "ajax", "nodejs"],
    advantages: ["Extremely simple and readable", "Language independent", "Lightweight", "Universal web API format"],
    disadvantages: ["No comments or metadata", "Limited data types", "No schema enforcement"],
    alternatives: ["xml", "yaml", "protobuf"],
    featured: true, relatedTrackId: "json",
  },
  {
    id: "xml", slug: "xml", name: "XML", nameBn: "এক্সএমএল",
    category: "Databases", subcategory: "Data Formats",
    logo: trackIcon("xml"), description: trackDescription("xml"),
    type: "Markup Language", difficulty: "beginner",
    organization: "W3C", releaseDate: "1998", currentVersion: "1.1",
    license: "Public Domain", officialWebsite: "https://www.w3.org/XML/",
    documentationUrl: "https://developer.mozilla.org/en-US/docs/Web/XML",
    tags: [...BASE_TAGS.database, "format", "markup", "structured-data"],
    relatedTechnologies: ["html", "json", "sql", "svg"],
    advantages: ["Self-descriptive", "Supports complex schemas (XSD)", "Extensible", "Widely used in enterprise"],
    disadvantages: ["Verbose syntax", "Large file sizes", "Parsing is slower than JSON"],
    alternatives: ["json", "yaml", "protobuf"],
    featured: true, relatedTrackId: "xml",
  },
  // ===== DEVOPS & CLOUD =====
  {
    id: "bash", slug: "bash", name: "Bash", nameBn: "ব্যাশ",
    category: "DevOps", subcategory: "Shell & Automation",
    logo: trackIcon("bash"), description: trackDescription("bash"),
    type: "Shell / Scripting Language", difficulty: "beginner",
    organization: "GNU Project", releaseDate: "1989", currentVersion: "5.2",
    license: "GPL-3", officialWebsite: "https://www.gnu.org/software/bash/",
    documentationUrl: "https://www.gnu.org/software/bash/manual/",
    programmingLanguage: "Bash",
    tags: ["devops", "shell", "automation", "scripting", "cli"],
    relatedTechnologies: ["aws", "git", "docker", "linux"],
    advantages: ["Automates repetitive tasks", "Most widely available shell", "Pipes and redirection", "Essential for server management"],
    disadvantages: ["Syntax can be cryptic", "No built-in data structures", "Error-prone"],
    alternatives: ["powershell", "python", "zsh"],
    featured: true, relatedTrackId: "bash",
  },
  {
    id: "aws", slug: "aws", name: "Amazon Web Services", nameBn: "এডব্লিউএস",
    category: "DevOps", subcategory: "Cloud Infrastructure",
    logo: trackIcon("aws"), description: trackDescription("aws"),
    type: "Cloud Platform", difficulty: "intermediate",
    organization: "Amazon", releaseDate: "2006",
    license: "Proprietary", officialWebsite: "https://aws.amazon.com/",
    documentationUrl: "https://docs.aws.amazon.com/",
    tags: ["devops", "cloud", "iaas", "paas", "infrastructure"],
    relatedTechnologies: ["bash", "docker", "nodejs", "python", "cybersecurity"],
    companiesUsing: ["Netflix", "Airbnb", "Stripe", "Slack", "Reddit"],
    advantages: ["Market-leading cloud provider", "Massive service catalog", "Global infrastructure", "Pay-as-you-go pricing"],
    disadvantages: ["Can get expensive", "Complex billing", "Steep learning curve"],
    alternatives: ["azure", "gcp", "vercel", "netlify"],
    featured: true, relatedTrackId: "aws",
  },
  {
    id: "docker", slug: "docker", name: "Docker", nameBn: "ডকার",
    category: "DevOps", subcategory: "Containerization",
    logo: "https://img.icons8.com/color/96/docker.png",
    description: "A platform for developing, shipping, and running applications inside lightweight containers.",
    type: "Containerization Platform", difficulty: "intermediate",
    organization: "Docker Inc.", releaseDate: "2013", currentVersion: "27",
    license: "Apache 2.0", officialWebsite: "https://www.docker.com/",
    githubRepo: "https://github.com/docker/docker-ce",
    documentationUrl: "https://docs.docker.com/",
    tags: ["devops", "container", "virtualization", "deployment"],
    relatedTechnologies: ["kubernetes", "aws", "bash", "linux"],
    advantages: ["Consistent environments", "Lightweight vs VMs", "Fast deployment", "Microservices friendly"],
    disadvantages: ["Not ideal for GUI apps", "Storage persistence can be tricky", "Network complexity"],
    alternatives: ["podman", "containerd", "lxc"],
    featured: true,
  },
  {
    id: "kubernetes", slug: "kubernetes", name: "Kubernetes", nameBn: "কুবেরনেটিস",
    category: "DevOps", subcategory: "Orchestration",
    logo: "https://img.icons8.com/color/96/kubernetes.png",
    description: "An open-source system for automating deployment, scaling, and management of containerized applications.",
    type: "Container Orchestration", difficulty: "advanced",
    organization: "CNCF", releaseDate: "2015", currentVersion: "1.31",
    license: "Apache 2.0", officialWebsite: "https://kubernetes.io/",
    githubRepo: "https://github.com/kubernetes/kubernetes",
    documentationUrl: "https://kubernetes.io/docs/",
    tags: ["devops", "container", "orchestration", "scaling"],
    relatedTechnologies: ["docker", "aws", "bash", "go"],
    advantages: ["Automated container orchestration", "Self-healing", "Horizontal scaling", "Service discovery"],
    disadvantages: ["Complex setup", "Steep learning curve", "Overkill for small projects"],
    alternatives: ["docker-swarm", "nomad", "aws-ecs"],
    featured: true,
  },
  {
    id: "git", slug: "git", name: "Git", nameBn: "গিট",
    category: "DevOps", subcategory: "Version Control",
    logo: "https://img.icons8.com/color/96/git.png",
    description: "A distributed version control system for tracking changes in source code during software development.",
    type: "Version Control System", difficulty: "beginner",
    organization: "Linus Torvalds / Git community", releaseDate: "2005", currentVersion: "2.47",
    license: "GPL-2", officialWebsite: "https://git-scm.com/",
    documentationUrl: "https://git-scm.com/doc",
    tags: ["devops", "vcs", "version-control", "collaboration"],
    relatedTechnologies: ["github", "gitlab", "bash", "ci-cd"],
    advantages: ["Distributed architecture", "Branching is fast", "Nearly every project uses it", "Offline work possible"],
    disadvantages: ["Steep learning curve for concepts", "Large binary files not ideal", "Can be confusing for beginners"],
    alternatives: ["mercurial", "subversion", "fossil"],
    featured: true,
  },
  // ===== DATA SCIENCE & AI =====
  {
    id: "numpy", slug: "numpy", name: "NumPy", nameBn: "নামপাই",
    category: "Data Science", subcategory: "Scientific Computing",
    logo: trackIcon("numpy"), description: trackDescription("numpy"),
    type: "Python Library", difficulty: "intermediate",
    organization: "NumPy Community", releaseDate: "2006", currentVersion: "2.1",
    license: "BSD", officialWebsite: "https://numpy.org/",
    githubRepo: "https://github.com/numpy/numpy",
    documentationUrl: "https://numpy.org/doc/",
    programmingLanguage: "Python",
    tags: [...BASE_TAGS.language, "data-science", "numerical", "array"],
    relatedTechnologies: ["python", "pandas", "scipy", "matplotlib", "machinelearning"],
    advantages: ["Fast numerical computations", "Foundation for all Python data tools", "Memory-efficient arrays", "Vectorized operations"],
    disadvantages: ["Python overhead for small operations", "Not GPU-accelerated by default"],
    alternatives: ["julia", "r", "torch"],
    featured: true, relatedTrackId: "numpy",
  },
  {
    id: "pandas", slug: "pandas", name: "Pandas", nameBn: "পান্ডাস",
    category: "Data Science", subcategory: "Data Analysis",
    logo: trackIcon("pandas"), description: trackDescription("pandas"),
    type: "Python Library", difficulty: "intermediate",
    organization: "NumFocus", releaseDate: "2008", currentVersion: "2.2",
    license: "BSD", officialWebsite: "https://pandas.pydata.org/",
    githubRepo: "https://github.com/pandas-dev/pandas",
    documentationUrl: "https://pandas.pydata.org/docs/",
    programmingLanguage: "Python",
    tags: [...BASE_TAGS.language, "data-science", "data-frame", "analysis"],
    relatedTechnologies: ["python", "numpy", "matplotlib", "scipy", "excel"],
    advantages: ["Powerful DataFrame structure", "Easy data manipulation", "Great CSV/Excel handling", "Rich I/O support"],
    disadvantages: ["Memory intensive for large datasets", "Slower than Polars", "Complex indexing"],
    alternatives: ["polars", "duckdb", "r-data-table"],
    featured: true, relatedTrackId: "pandas",
  },
  {
    id: "scipy", slug: "scipy", name: "SciPy", nameBn: "সাইপাই",
    category: "Data Science", subcategory: "Scientific Computing",
    logo: trackIcon("scipy"), description: trackDescription("scipy"),
    type: "Python Library", difficulty: "advanced",
    organization: "NumFocus", releaseDate: "2001", currentVersion: "1.14",
    license: "BSD", officialWebsite: "https://scipy.org/",
    githubRepo: "https://github.com/scipy/scipy",
    documentationUrl: "https://docs.scipy.org/doc/scipy/",
    programmingLanguage: "Python",
    tags: [...BASE_TAGS.language, "data-science", "scientific", "optimization"],
    relatedTechnologies: ["python", "numpy", "pandas", "matplotlib"],
    advantages: ["Comprehensive scientific tools", "Optimization algorithms", "Signal processing", "Statistical functions"],
    disadvantages: ["Can be overwhelming", "Some modules are outdated"],
    alternatives: ["scikit-learn", "julia", "r"],
    featured: true, relatedTrackId: "scipy",
  },
  {
    id: "matplotlib", slug: "matplotlib", name: "Matplotlib", nameBn: "ম্যাটপ্লটলিব",
    category: "Data Science", subcategory: "Data Visualization",
    logo: trackIcon("matplotlib"), description: trackDescription("matplotlib"),
    type: "Python Library", difficulty: "intermediate",
    organization: "NumFocus / John Hunter", releaseDate: "2003", currentVersion: "3.9",
    license: "BSD", officialWebsite: "https://matplotlib.org/",
    githubRepo: "https://github.com/matplotlib/matplotlib",
    documentationUrl: "https://matplotlib.org/stable/",
    programmingLanguage: "Python",
    tags: [...BASE_TAGS.language, "data-science", "visualization", "plotting"],
    relatedTechnologies: ["python", "numpy", "pandas", "seaborn"],
    advantages: ["Publication-quality plots", "Highly customizable", "Wide chart type support", "Matlab-like API"],
    disadvantages: ["Imperative API can be verbose", "Complex layouts are difficult", "Slower with many data points"],
    alternatives: ["plotly", "seaborn", "d3-js"],
    featured: true, relatedTrackId: "matplotlib",
  },
  {
    id: "statistic", slug: "statistics", name: "Statistics", nameBn: "স্ট্যাটিস্টিক্স",
    category: "Data Science", subcategory: "Fundamentals",
    logo: trackIcon("statistic"), description: trackDescription("statistic"),
    type: "Mathematical Science", difficulty: "beginner",
    tags: [...BASE_TAGS.language, "data-science", "statistics", "math"],
    relatedTechnologies: ["python", "numpy", "pandas", "machinelearning", "r"],
    advantages: ["Foundation for data science", "Essential for ML", "Evidence-based decision making"],
    disadvantages: ["Can be complex", "Abstract concepts"],
    alternatives: [],
    featured: true, relatedTrackId: "statistic",
  },
  {
    id: "machinelearning", slug: "machine-learning", name: "Machine Learning", nameBn: "মেশিন লার্নিং",
    category: "AI & ML", subcategory: "Machine Learning",
    logo: trackIcon("machinelearning"), description: trackDescription("machinelearning"),
    type: "Field of AI", difficulty: "advanced",
    releaseDate: "1959",
    tags: ["ai", "machine-learning", "data-science", "algorithms"],
    relatedTechnologies: ["python", "numpy", "pandas", "ai", "genai", "scipy"],
    advantages: ["Automates decision making", "Finds patterns in data", "Improves with more data", "Wide industry applications"],
    disadvantages: ["Requires large datasets", "Black-box models can be opaque", "Bias in training data"],
    alternatives: [],
    featured: true, relatedTrackId: "machinelearning",
  },
  {
    id: "ai", slug: "artificial-intelligence", name: "Artificial Intelligence", nameBn: "কৃত্রিম বুদ্ধিমত্তা",
    category: "AI & ML", subcategory: "Artificial Intelligence",
    logo: trackIcon("ai"), description: trackDescription("ai"),
    type: "Field of Computer Science", difficulty: "advanced",
    releaseDate: "1956",
    tags: ["ai", "machine-learning", "deep-learning", "intelligence"],
    relatedTechnologies: ["python", "machinelearning", "genai", "numpy"],
    advantages: ["Automates complex tasks", "24/7 operation", "Handles huge data volumes", "Improves efficiency"],
    disadvantages: ["High implementation cost", "Data dependency", "Ethical concerns", "Job displacement worries"],
    alternatives: [],
    featured: true, relatedTrackId: "ai",
  },
  {
    id: "genai", slug: "generative-ai", name: "Generative AI", nameBn: "জেনারেটিভ এআই",
    category: "AI & ML", subcategory: "Generative AI",
    logo: trackIcon("genai"), description: trackDescription("genai"),
    type: "Field of AI", difficulty: "advanced",
    releaseDate: "2020",
    tags: ["ai", "generative", "llm", "content-creation"],
    relatedTechnologies: ["python", "machinelearning", "ai", "openai"],
    advantages: ["Creates original content", "Code generation", "Image/video generation", "Natural conversation"],
    disadvantages: ["Can produce incorrect information", "Copyright concerns", "High computational cost"],
    alternatives: [],
    featured: true, relatedTrackId: "genai",
  },
  // ===== PRODUCTIVITY =====
  {
    id: "excel", slug: "excel", name: "Microsoft Excel", nameBn: "মাইক্রোসফট এক্সেল",
    category: "Productivity", subcategory: "Spreadsheets",
    logo: trackIcon("excel"), description: trackDescription("excel"),
    type: "Spreadsheet Software", difficulty: "beginner",
    organization: "Microsoft", releaseDate: "1985", currentVersion: "Microsoft 365",
    license: "Proprietary", officialWebsite: "https://www.microsoft.com/microsoft-365/excel",
    documentationUrl: "https://support.microsoft.com/excel",
    tags: ["productivity", "spreadsheet", "data-analysis", "office"],
    relatedTechnologies: ["google-sheets", "pandas", "sql"],
    advantages: ["Widely used in business", "Powerful formulas and pivot tables", "Charting capabilities", "VBA automation"],
    disadvantages: ["Limited for large datasets", "Proprietary format", "Not designed for real-time collaboration (classic)"],
    alternatives: ["google-sheets", "libreoffice-calc", "pandas"],
    featured: true, relatedTrackId: "excel",
  },
  {
    id: "google-sheets", slug: "google-sheets", name: "Google Sheets", nameBn: "গুগল শীটস",
    category: "Productivity", subcategory: "Spreadsheets",
    logo: trackIcon("google-sheets"), description: trackDescription("google-sheets"),
    type: "Spreadsheet Software", difficulty: "beginner",
    organization: "Google", releaseDate: "2006",
    license: "Proprietary (Free tier)", officialWebsite: "https://www.google.com/sheets/about/",
    documentationUrl: "https://support.google.com/a/users/answer/9282959",
    tags: ["productivity", "spreadsheet", "data-analysis", "collaboration"],
    relatedTechnologies: ["excel", "pandas", "google-apps-script"],
    advantages: ["Real-time collaboration", "Free to use", "Cloud-based", "Google Apps Script automation"],
    disadvantages: ["Less powerful than Excel", "Processing limits", "Fewer formula functions"],
    alternatives: ["excel", "airtable", "notion"],
    featured: true, relatedTrackId: "google-sheets",
  },
  // ===== SECURITY =====
  {
    id: "cybersecurity", slug: "cybersecurity", name: "Cybersecurity", nameBn: "সাইবার নিরাপত্তা",
    category: "Security", subcategory: "Security Engineering",
    logo: trackIcon("cybersecurity"), description: trackDescription("cybersecurity"),
    type: "Field of Computer Science", difficulty: "advanced",
    tags: ["security", "hacking", "protection", "networking"],
    relatedTechnologies: ["bash", "aws", "python", "networking"],
    advantages: ["Protects digital assets", "High demand career", "Continuous learning", "Critical infrastructure protection"],
    disadvantages: ["Constantly evolving threats", "High responsibility", "Can be stressful"],
    alternatives: [],
    featured: true, relatedTrackId: "cybersecurity",
  },
  // ===== COMPUTER SCIENCE =====
  {
    id: "dsa", slug: "data-structures-algorithms", name: "Data Structures & Algorithms", nameBn: "ডাটা স্ট্রাকচার ও অ্যালগরিদম",
    category: "Computer Science", subcategory: "Algorithms & Data Structures",
    logo: trackIcon("dsa"), description: trackDescription("dsa"),
    type: "Computer Science Fundamentals", difficulty: "intermediate",
    tags: ["cs", "algorithms", "data-structures", "problem-solving"],
    relatedTechnologies: ["python", "c", "cpp", "java", "go", "rust"],
    advantages: ["Foundation of all programming", "Coding interview essential", "Improves problem-solving skills", "Language-independent concepts"],
    disadvantages: ["Can feel abstract", "Requires practice", "Some concepts are mathematically heavy"],
    alternatives: [],
    featured: true, relatedTrackId: "dsa",
  },
  // ===== HARDWARE & IOT =====
  {
    id: "raspberry_pi", slug: "raspberry-pi", name: "Raspberry Pi & IoT", nameBn: "রাস্পবেরি পাই ও আইওটি",
    category: "Hardware & IoT", subcategory: "Embedded Systems",
    logo: trackIcon("raspberry_pi"), description: trackDescription("raspberry_pi"),
    type: "Single-board Computer / IoT Platform", difficulty: "intermediate",
    organization: "Raspberry Pi Foundation", releaseDate: "2012", currentVersion: "Raspberry Pi 5",
    license: "Various", officialWebsite: "https://www.raspberrypi.com/",
    documentationUrl: "https://www.raspberrypi.com/documentation/",
    tags: ["hardware", "iot", "embedded", "linux", "electronics"],
    relatedTechnologies: ["python", "bash", "c", "linux"],
    advantages: ["Affordable computing", "Great for learning hardware", "GPIO for physical computing", "Large community"],
    disadvantages: ["Limited processing power", "Not real-time", "Peripherals required"],
    alternatives: ["arduino", "esp32", "jetson-nano"],
    featured: true, relatedTrackId: "raspberry_pi",
  },
  // ===== CYBERPUNK FOUNDATIONS =====
  {
    id: "intro-programming", slug: "intro-programming", name: "Intro to Programming", nameBn: "প্রোগ্রামিং পরিচিতি",
    category: "Computer Science", subcategory: "Fundamentals",
    logo: trackIcon("intro-programming"), description: trackDescription("intro-programming"),
    type: "Learning Track", difficulty: "beginner",
    tags: ["programming", "beginner", "fundamentals", "cs"],
    relatedTechnologies: ["typing-speed", "codegame", "python"],
    advantages: [], disadvantages: [], alternatives: [],
    featured: false, relatedTrackId: "intro-programming",
  },
  {
    id: "typing-speed", slug: "typing-speed", name: "Typing Speed Test", nameBn: "টাইপিং স্পিড টেস্ট",
    category: "Computer Science", subcategory: "Fundamentals",
    logo: trackIcon("typing-speed"), description: trackDescription("typing-speed"),
    type: "Learning Tool", difficulty: "beginner",
    tags: ["typing", "beginner", "skill"],
    relatedTechnologies: ["intro-programming", "codegame"],
    advantages: [], disadvantages: [], alternatives: [],
    featured: false, relatedTrackId: "typing-speed",
  },
  {
    id: "codegame", slug: "codegame", name: "CodeGame", nameBn: "কোডগেম",
    category: "Computer Science", subcategory: "Fundamentals",
    logo: trackIcon("codegame"), description: trackDescription("codegame"),
    type: "Learning Game", difficulty: "beginner",
    tags: ["game", "beginner", "coding", "fun"],
    relatedTechnologies: ["intro-programming", "typing-speed"],
    advantages: [], disadvantages: [], alternatives: [],
    featured: false, relatedTrackId: "codegame",
  },
];

all.forEach(entry => {
  technologies[entry.id] = entry;
});

export function getTechnology(slug: string): TechnologyEntry | undefined {
  return Object.values(technologies).find(t => t.slug === slug || t.id === slug);
}

export function getTechnologyById(id: string): TechnologyEntry | undefined {
  return technologies[id];
}

export function getTechnologiesByCategory(category: string): TechnologyEntry[] {
  return Object.values(technologies).filter(t => t.category === category);
}

export function getTechnologiesBySubcategory(category: string, subcategory: string): TechnologyEntry[] {
  return Object.values(technologies).filter(t => t.category === category && t.subcategory === subcategory);
}

export function getAllCategories(): string[] {
  return [...new Set(Object.values(technologies).map(t => t.category))];
}

export function getAllSubcategories(category: string): string[] {
  return [...new Set(Object.values(technologies).filter(t => t.category === category).map(t => t.subcategory))];
}

export function getFeaturedTechnologies(): TechnologyEntry[] {
  return Object.values(technologies).filter(t => t.featured);
}

export function searchTechnologies(query: string): TechnologyEntry[] {
  const q = query.toLowerCase();
  return Object.values(technologies).filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.tags.some(tag => tag.includes(q)) ||
    t.category.toLowerCase().includes(q) ||
    t.subcategory.toLowerCase().includes(q) ||
    t.description.toLowerCase().includes(q)
  );
}
