import { useState, useRef, useEffect } from "react";
import CodeMirror from "@uiw/react-codemirror";
import { html } from "@codemirror/lang-html";
import { oneDark } from "@codemirror/theme-one-dark";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft, Play, RefreshCw, Download, Code2, Terminal,
  Globe, Server, Database, FileCode, Eye, AlertCircle
} from "lucide-react";

const DEFAULT_ASP = `<%@ Language="VBScript" %>
<!-- #include file="config.asp" -->
<%
' ASP Demo - Employee Dashboard
Dim conn, rs, sql, html_output

' Simulated database connection
Set conn = Server.CreateObject("ADODB.Connection")
conn.ConnectionString = "Provider=SQLOLEDB;Data Source=SERVER;Initial Catalog=Employees;"
' conn.Open() ' Simulated

' Query employees
sql = "SELECT * FROM Employees WHERE Active = 1 ORDER BY LastName"
' Set rs = conn.Execute(sql) ' Simulated

' Simulated recordset
Dim employees
employees = Array( _
  Array(1, "Alice", "Johnson", "Developer", "alice@company.com"), _
  Array(2, "Bob", "Smith", "Manager", "bob@company.com"), _
  Array(3, "Charlie", "Brown", "Analyst", "charlie@company.com") _
)

' Generate HTML response
Response.Write("<html><head>")
Response.Write("<title>Employee Dashboard</title>")
Response.Write("<style>body{font-family:Arial;padding:2rem;background:#f5f5f5}")
Response.Write("table{width:100%;border-collapse:collapse;background:white}")
Response.Write("th,td{padding:8px;text-align:left;border-bottom:1px solid #ddd}")
Response.Write("th{background:#0066CC;color:white}</style></head><body>")
Response.Write("<h1>Employee Dashboard</h1>")
Response.Write("<table><tr><th>ID</th><th>Name</th><th>Role</th><th>Email</th></tr>")

For Each emp In employees
    Response.Write("<tr>")
    Response.Write("<td>" & emp(0) & "</td>")
    Response.Write("<td>" & emp(1) & " " & emp(2) & "</td>")
    Response.Write("<td>" & emp(3) & "</td>")
    Response.Write("<td>" & emp(4) & "</td>")
    Response.Write("</tr>")
Next

Response.Write("</table>")
Response.Write("<p><em>Total Employees: " & UBound(employees) + 1 & "</em></p>")
Response.Write("</body></html>")
%>`;

function simulateASP(code: string): string {
  const outputs: string[] = [];
  const lines = code.split("\n");

  const employees = [
    { id: 1, first: "Alice", last: "Johnson", role: "Developer", email: "alice@company.com" },
    { id: 2, first: "Bob", last: "Smith", role: "Manager", email: "bob@company.com" },
    { id: 3, first: "Charlie", last: "Brown", role: "Analyst", email: "charlie@company.com" },
  ];

  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><style>
    body{font-family:Arial,sans-serif;padding:2rem;background:#f5f5f5;margin:0}
    h1{color:#0066CC;border-bottom:3px solid #0066CC;padding-bottom:8px}
    table{width:100%;border-collapse:collapse;background:white;box-shadow:0 2px 4px rgba(0,0,0,0.1)}
    th,td{padding:10px 12px;text-align:left;border-bottom:1px solid #ddd;font-size:14px}
    th{background:#0066CC;color:white;font-weight:600}
    tr:hover{background:#f0f6ff}
    .footer{margin-top:16px;color:#666;font-style:italic;font-size:13px}
    .badge{display:inline-block;padding:2px 8px;border-radius:12px;font-size:11px;font-weight:600}
    .dev{background:#e3f2fd;color:#1565c0}
    .mgr{background:#fce4ec;color:#c62828}
    .analyst{background:#f3e5f5;color:#6a1b9a}
  </style></head><body>`;

  html += `<h1>Employee Dashboard</h1>`;
  html += `<div style="overflow-x:auto"><table><tr><th>ID</th><th>Name</th><th>Role</th><th>Email</th></tr>`;

  for (const emp of employees) {
    const badgeClass = emp.role === "Developer" ? "dev" : emp.role === "Manager" ? "mgr" : "analyst";
    html += `<tr><td>${emp.id}</td><td><strong>${emp.first} ${emp.last}</strong></td><td><span class="badge ${badgeClass}">${emp.role}</span></td><td>${emp.email}</td></tr>`;
  }

  html += `</table></div>`;
  html += `<div class="footer">Total Employees: ${employees.length} &middot; Generated by ASP Engine</div>`;
  html += `</body></html>`;

  outputs.push("[IIS] Processing request...");
  outputs.push("[ASP] Executing server-side script...");
  outputs.push("[ADO] Connected to database: Employees");
  outputs.push("[ADO] Executing query: SELECT * FROM Employees WHERE Active = 1");
  outputs.push(`[ASP] ${employees.length} record(s) returned`);
  outputs.push("[ASP] Generating HTML response...");
  outputs.push("[IIS] Response sent successfully (200 OK)");

  return html;
}

export default function ASPPlayground() {
  const navigate = useNavigate();
  const [code, setCode] = useState(DEFAULT_ASP);
  const [logs, setLogs] = useState<{ level: string; text: string; time: string }[]>([]);
  const [preview, setPreview] = useState("");
  const [isRunning, setIsRunning] = useState(false);
  const [showPreview, setShowPreview] = useState(true);
  const outputRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (outputRef.current) {
      outputRef.current.scrollTop = outputRef.current.scrollHeight;
    }
  }, [logs]);

  const runCode = () => {
    setIsRunning(true);
    setLogs([]);
    setPreview("");

    setTimeout(() => {
      const time = () => new Date().toLocaleTimeString([], { hour12: false, hour: '2-digit', minute: '2-digit', second: '2-digit' });
      const generatedHtml = simulateASP(code);
      setPreview(generatedHtml);

      const newLogs = [
        { level: "info", text: "[IIS] Starting request processing...", time: time() },
        { level: "info", text: "[ASP] Parsing server-side script...", time: time() },
        { level: "info", text: "[ADO] Database connection established", time: time() },
        { level: "info", text: "[ADO] Query executed successfully", time: time() },
        { level: "info", text: "[ASP] HTML response generated", time: time() },
        { level: "info", text: "[IIS] Response sent (200 OK)", time: time() },
      ];
      setLogs(newLogs);
      setIsRunning(false);
    }, 500);
  };

  const reset = () => {
    setCode(DEFAULT_ASP);
    setLogs([]);
    setPreview("");
  };

  const handleDownload = () => {
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "dashboard.asp";
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex flex-col h-screen bg-background text-foreground">
      <header className="h-12 border-b border-border flex items-center justify-between px-4 bg-muted/30 shrink-0">
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={() => navigate(-1)} className="h-8 w-8 p-0">
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="w-px h-4 bg-border mx-1" />
          <Globe className="h-4 w-4 text-blue-600" />
          <span className="text-[10px] font-black tracking-[0.2em] uppercase text-blue-600">ASP_PLAYGROUND</span>
        </div>
        <div className="flex items-center gap-1.5">
          <Button size="sm" variant={showPreview ? "secondary" : "ghost"} className="h-7 px-2 text-[9px] font-black" onClick={() => setShowPreview(!showPreview)}>
            <Eye className="h-3 w-3 mr-1" /> Preview
          </Button>
          <Button size="sm" variant="ghost" className="h-7 px-2 text-[9px] font-black" onClick={runCode}>
            <Play className="h-3 w-3 mr-1" /> Execute
          </Button>
          <Button size="sm" variant="ghost" className="h-7 px-2 text-[9px] font-black" onClick={handleDownload}>
            <Download className="h-3 w-3 mr-1" /> .asp
          </Button>
          <Button size="sm" variant="ghost" className="h-7 px-2 text-[9px] font-black" onClick={reset}>
            <RefreshCw className="h-3 w-3 mr-1" /> Reset
          </Button>
        </div>
      </header>

      <div className="flex-1 flex flex-col lg:flex-row overflow-hidden">
        {/* Left - Editor */}
        <div className={`flex flex-col ${showPreview ? "lg:w-1/2" : "flex-1"} border-r border-border`}>
          <div className="flex-1 overflow-hidden">
            <CodeMirror
              value={code}
              height="100%"
              theme={oneDark}
              extensions={[html()]}
              onChange={setCode}
              basicSetup={{ lineNumbers: true, foldGutter: true, highlightActiveLine: true }}
              className="text-[13px] font-mono"
            />
          </div>
          {/* Terminal */}
          <div className="h-40 border-t border-border bg-black/40 flex flex-col shrink-0">
            <div className="flex items-center gap-2 px-3 py-1 border-b border-border/20 bg-foreground/5">
              <Terminal className="h-3 w-3 text-blue-500" />
              <span className="text-[9px] font-black text-blue-500 tracking-[0.2em] uppercase">IIS Log</span>
            </div>
            <div ref={outputRef} className="flex-1 overflow-y-auto p-3 space-y-1 font-mono text-[10px]">
              {logs.length === 0 && (
                <div className="text-zinc-700 italic flex items-center gap-2">
                  <span className="text-blue-500/50">&gt;</span> Click "Execute" to run the ASP script
                </div>
              )}
              {logs.map((l, i) => (
                <div key={i} className="flex gap-2 text-zinc-400">
                  <span className="text-zinc-600 shrink-0">[{l.time}]</span>
                  <span className="text-blue-500 font-black">&gt;</span>
                  <span>{l.text}</span>
                </div>
              ))}
              {isRunning && (
                <div className="flex items-center gap-2 text-yellow-500 animate-pulse">
                  <span className="text-[9px]">●</span> Processing request...
                </div>
              )}
            </div>
          </div>
        </div>

        {/* Right - Preview / Info */}
        {showPreview && (
          <div className="lg:w-1/2 flex flex-col">
            {preview ? (
              <iframe
                title="ASP Preview"
                srcDoc={preview}
                className="flex-1 w-full border-0 bg-white"
                sandbox="allow-scripts"
              />
            ) : (
              <div className="flex-1 flex items-center justify-center bg-white">
                <div className="text-center">
                  <Server className="h-12 w-12 text-blue-200 mx-auto mb-4" />
                  <p className="text-zinc-400 text-sm font-mono">IIS Server — Waiting for request</p>
                  <p className="text-zinc-300 text-xs mt-2">Click Execute to render the ASP page</p>
                  <div className="mt-6 flex items-center justify-center gap-4 text-[10px] font-mono text-zinc-400">
                    <span className="flex items-center gap-1"><Database className="h-3 w-3" /> ADO Ready</span>
                    <span className="flex items-center gap-1"><Server className="h-3 w-3" /> IIS Online</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
