  ["c1","What Is Cloud Computing?","ক্লাউড কম্পিউটিং কী?","Cloud Foundations",[
    ["s1","lesson","Cloud Computing Defined","Cloud computing is the on-demand delivery of compute power, database storage, applications, and other IT resources via the internet with pay-as-you-go pricing. Instead of buying, owning, and maintaining physical data centers and servers, you can access technology services on an as-needed basis from a cloud provider like Amazon Web Services (AWS). This model transforms capital expenditure into operational expenditure. The National Institute of Standards and Technology defines five essential characteristics: on-demand self-service, broad network access, resource pooling, rapid elasticity, and measured service. These characteristics enable organizations to innovate faster, scale globally, and reduce costs compared to traditional on-premises infrastructure deployments."],
    ["s2","lesson","Service Models IaaS PaaS SaaS","Cloud computing offers three primary service models. Infrastructure as a Service provides virtualized computing resources over the internet such as virtual machines, storage, and networks. You manage the operating system, middleware, and applications while the provider manages the physical hardware. Platform as a Service removes the need to manage underlying infrastructure, allowing you to focus on deploying and managing applications. The provider handles the operating system, runtime, and middleware. Software as a Service delivers fully functional software applications over the internet on a subscription basis. You simply use the application while the provider manages everything. AWS offers services across all three models including EC2 for IaaS, Elastic Beanstalk for PaaS, and WorkDocs for SaaS."],
    ["s3","lesson","Deployment Models Public Private Hybrid","Cloud deployments generally follow three distinct models. Public cloud services are delivered over the public internet and shared across multiple organizations, offering scalability and cost efficiency. AWS, Azure, and GCP are the major public cloud providers. Private cloud infrastructure is used exclusively by a single organization, either on-premises or hosted by a third party, providing greater control and security for sensitive workloads. Hybrid cloud combines public and private clouds, allowing data and applications to be shared between them, offering flexibility, compliance, and workload portability. Many enterprises adopt a multi-cloud strategy, using multiple public cloud providers to avoid vendor lock-in and leverage best-in-class services from different providers."],
    ["s4","lesson","Benefits and Business Value of Cloud Computing","Adopting cloud computing delivers measurable business benefits for organizations of all sizes. First, trade capital expense for variable expense: instead of investing heavily in data centers and servers before knowing how you will use them, you pay only when you consume computing resources. Second, benefit from massive economies of scale: providers like AWS aggregate usage across hundreds of thousands of customers, achieving lower pay-as-you-go prices. Third, stop guessing capacity: you can scale up or down instantly based on demand, eliminating costly over-provisioning or under-utilization. Fourth, increase speed and agility: new IT resources are a click away, reducing the time to experiment from weeks to minutes. Fifth, go global in minutes: deploy applications in multiple regions worldwide with minimal effort."],
    ["s5","quiz","Which cloud characteristic allows resources to be automatically scaled based on demand?","Rapid elasticity,On-demand self-service,Resource pooling,Measured service",0,"Rapid elasticity enables resources to scale automatically and elastically based on demand, which is one of the five essential characteristics defined by NIST for cloud computing."],
    ["s6","exercise","Compare Cloud vs On-Premises","Create a table comparing capital expenditure versus operational expenditure between traditional on-premises data centers and cloud computing. List at least 5 differences including cost structure, scalability, maintenance, time-to-market, and global reach."]
  ]],
  ["c2","AWS Overview","AWS ওভারভিউ","Cloud Foundations",[
    ["s1","lesson","What Is AWS","Amazon Web Services is the world most comprehensive and broadly adopted cloud platform, offering over 200 fully featured services from data centers globally. Launched in 2006, AWS provides infrastructure services like compute, storage, and databases, as well as emerging technologies such as machine learning, artificial intelligence, Internet of Things, and serverless computing. AWS serves millions of customers worldwide, including startups, enterprises, and government agencies. The platform operates on a pay-as-you-go pricing model with no upfront commitments or long-term contracts. AWS global infrastructure spans over 30 geographic regions and more than 100 Availability Zones, making it one of the largest cloud providers by both service breadth and infrastructure footprint globally."],
    ["s2","lesson","AWS Service Categories","AWS organizes its services into several categories for easy navigation. Compute services include EC2 for virtual machines, Lambda for serverless functions, and ECS and EKS for container orchestration. Storage services include S3 for object storage, EBS for block storage, EFS for file storage, and S3 Glacier for archival storage. Database services include RDS for relational databases, DynamoDB for NoSQL, ElastiCache for in-memory caching, and Redshift for data warehousing. Networking services include VPC for virtual private cloud, CloudFront for content delivery, Route 53 for DNS, and API Gateway for APIs. Security services include IAM for identity and access management, KMS for encryption, and AWS WAF for application protection."],
    ["s3","lesson","AWS Management Interfaces","AWS provides multiple ways to interact with its services. The AWS Management Console is a web-based graphical user interface that lets you manage services through a browser, ideal for exploration and manual configuration. The AWS Command Line Interface is a unified tool for managing services from the command line, enabling scripting and automation of repetitive tasks. AWS Software Development Kits provide language-specific APIs for services like Python via boto3, JavaScript, Java, .NET, and Go, allowing you to integrate AWS services directly into your applications. AWS CloudFormation and Terraform enable infrastructure as code, where you define resources in template files and provision them programmatically. AWS CDK offers additional programmatic control."],
    ["s4","lesson","AWS Free Tier and Getting Started Guide","The AWS Free Tier provides free limited access to many AWS services for new customers for 12 months after sign-up. It includes three types of offers: Always Free services like Lambda up to 1 million requests per month and DynamoDB up to 25 GB of storage, 12-Month Free services like EC2 750 hours per month of t2.micro instances and S3 5 GB of standard storage, and Trials for services like SageMaker and Amazon Connect. The Free Tier allows hands-on learning without financial commitment and is ideal for building proof-of-concept projects. AWS also offers training resources including AWS Skill Builder, digital courses, labs, and the AWS re:Post community forum for asking questions and sharing knowledge."],
    ["s5","quiz","How many Availability Zones does a typical AWS Region contain?","At least 1,At least 2,At least 3,Exactly 3",2,"Each AWS Region has at least 3 Availability Zones, with most regions having 3 or more for high availability and fault tolerance against data center failures."],
    ["s6","exercise","Explore AWS Services Menu","Sign in to the AWS Management Console and explore the Services menu. Identify one service from each category: Compute, Storage, Database, Networking, and Security. Write a brief description of each service and its primary use case in cloud architecture."]
  ]],
  ["c3","Global Infrastructure","গ্লোবাল ইনফ্রাস্ট্রাকচার","Cloud Foundations",[
    ["s1","lesson","AWS Global Infrastructure Overview","AWS global infrastructure is built around Regions and Availability Zones. A Region is a geographic area that contains multiple isolated locations known as Availability Zones. Each AZ consists of one or more physically separated data centers with independent power, cooling, and networking. AWS operates over 30 Regions and more than 100 Availability Zones worldwide, with additional regions announced for Canada, Israel, New Zealand, and Thailand. This global footprint enables customers to deploy applications close to their users for low latency while achieving high availability through data replication across multiple AZs. The infrastructure is designed to meet the highest standards for security, compliance, and operational resilience for enterprise workloads and mission-critical applications."],
    ["s2","lesson","Edge Locations and Points of Presence","In addition to Regions and AZs, AWS maintains a global network of Edge Locations and Points of Presence for content delivery and latency-sensitive applications. Edge Locations are used by Amazon CloudFront to cache content closer to end users, improving performance for static and dynamic content delivery globally. AWS also operates Regional Edge Caches for content that is less frequently accessed but still benefits from edge caching. The global network spans over 600 CloudFront Points of Presence and over 100 Direct Connect locations, providing secure, high-bandwidth connectivity to AWS services. Edge Locations also support AWS WAF, AWS Shield for DDoS protection, and Lambda at the Edge for running serverless functions at the network edge."],
    ["s3","lesson","Choosing the Right AWS Region","Selecting an AWS Region for your workloads requires considering several factors. Data residency and compliance: certain regulations require data to remain within specific geographic boundaries, such as GDPR in Europe or data localization laws in India and China. Latency: deploy applications in regions closest to your user base to minimize network latency, for example use ap-southeast-1 in Singapore for Southeast Asian users. Service availability: not all services are available in every region, new services often launch first in US East and roll out to other regions over time. Pricing: service costs vary by region due to differences in energy costs, taxes, and operational expenses. For production workloads, a multi-region strategy may be needed for disaster recovery and business continuity."],
    ["s4","lesson","Regional Services vs Global Services","AWS services are categorized as either regional or global. Regional services operate within a specific AWS Region and resources are isolated to that region. For example, an EC2 instance launched in us-east-1 cannot communicate with resources in eu-west-1 without cross-region networking. Regional services include EC2, S3 (bucket names are global but data is regional), RDS, DynamoDB, and Lambda. Global services operate across all regions from a single control plane. These include IAM as user permissions apply globally, Route 53 for DNS service, CloudFront for content delivery, and AWS WAF. Understanding this distinction is critical for architecture design. Using global services for identity and DNS ensures consistency, while regional services keep data within compliance boundaries."],
    ["s5","quiz","What is the primary purpose of AWS Availability Zones within a Region?","To provide content caching,To enable high availability and fault tolerance,To reduce data transfer costs,To comply with data residency requirements",1,"Availability Zones are physically separated data centers within a Region that provide high availability and fault tolerance through isolation from infrastructure failures."],
    ["s6","exercise","Map AWS Regions Worldwide","Visit the AWS Global Infrastructure page and identify the regions available in North America, Europe, Asia Pacific, and South America. List at least 3 regions per continent with their region codes such as us-east-1 or eu-west-2."]
  ]],
  ["c4","Regions and Availability Zones","রিজিওন এবং অ্যাভেইলেবিলিটি জোন","Cloud Foundations",[
    ["s1","lesson","Region Architecture Deep Dive","An AWS Region is a geographically distinct area consisting of multiple isolated Availability Zones connected through low-latency, high-throughput, and redundant networking. Each region operates independently with its own set of services and pricing. The naming convention follows patterns like us-east-1 for US East N. Virginia, eu-west-1 for EU West Ireland, and ap-southeast-1 for Asia Pacific Singapore. Regions are isolated from each other to ensure the highest possible fault tolerance and stability. A failure in one region does not impact another region. This isolation is intentional and provides the strongest possible separation for disaster recovery and compliance. Data does not automatically replicate across regions unless you explicitly configure cross-region replication."],
    ["s2","lesson","Availability Zone Architecture","Each Availability Zone consists of one or more discrete data centers with redundant power, networking, and connectivity, housed in separate facilities. AZs in the same region are connected through redundant, low-latency fiber links between them, enabling synchronous replication and high availability architectures. The distance between AZs is carefully planned, typically a few kilometers apart, close enough for low latency replication but far enough to prevent correlated failures from natural disasters or utility outages. By distributing application instances across multiple AZs, you can protect against data center failures and achieve high availability. This is the foundation of AWS fault-tolerant design: run your application in at least two AZs to survive an AZ-level outage."],
    ["s3","lesson","Designing for High Availability with AZs","Building resilient architectures on AWS requires leveraging multiple Availability Zones. A common pattern is the multi-AZ deployment: launch EC2 instances across three AZs behind an Application Load Balancer, use a multi-AZ RDS database with a standby replica in a different AZ, and store data in S3 which automatically replicates across at least three AZs within a region. For stateless applications, this is straightforward, the load balancer routes traffic to healthy instances in any AZ. For stateful applications, use managed services like ElastiCache or DynamoDB that handle replication across AZs automatically. This design achieves 99.99 percent availability and protects against the most common failure scenarios in cloud computing."],
    ["s4","lesson","Local Zones Wavelength and Outposts","AWS offers additional infrastructure types for specific use cases. Local Zones place compute, storage, and database services closer to large population centers not covered by existing regions, ideal for latency-sensitive applications like media streaming and real-time gaming. Wavelength Zones embed AWS compute and storage at 5G network edge locations, enabling ultra-low latency for applications like autonomous vehicles and industrial IoT. AWS Outposts brings native AWS services, infrastructure, and operating models to virtually any on-premises or edge location, providing a consistent hybrid experience. These extensions of the AWS infrastructure allow you to deploy workloads with single-digit millisecond latency requirements while meeting data residency constraints."],
    ["s5","quiz","What is the minimum number of Availability Zones an AWS Region must have?","1,2,3,4",2,"Every AWS Region consists of at least 3 Availability Zones to ensure high availability and fault tolerance for customer workloads across isolated data centers."],
    ["s6","exercise","Design a Multi-AZ Architecture","Draw a diagram showing a web application deployed across 3 Availability Zones with an Application Load Balancer, EC2 instances, and an RDS Multi-AZ database. Explain how this design achieves fault tolerance and high availability when a single AZ fails completely."]
  ]],
  ["c5","Shared Responsibility Model","শেয়ার্ড রেসপনসিবিলিটি মডেল","Cloud Foundations",[
    ["s1","lesson","Understanding the Shared Responsibility Model","The Shared Responsibility Model is a fundamental security framework that defines what AWS is responsible for and what the customer is responsible for. AWS is responsible for security OF the cloud, which includes the physical infrastructure such as data centers, hardware, and networking cables, the hypervisor layer, and managed services like S3, DynamoDB, and Lambda. The customer is responsible for security IN the cloud, which includes operating system patches, application code, firewall rules, IAM permissions, data encryption, and network traffic protection. This shared model is essential because it determines where your security obligations begin and end. Misunderstanding this boundary is one of the most common causes of security incidents."],
    ["s2","lesson","AWS Responsibilities Security OF the Cloud","AWS is responsible for protecting the infrastructure that runs all AWS services. This includes physical data center security with multiple layers of access controls including 24/7 surveillance, biometric authentication, and two-factor access. AWS manages the hardware, software, and networking components that power its services, including regular patching of the hypervisor layer and underlying operating systems. For managed services like RDS and DynamoDB, AWS handles database software patching and backup automation. AWS also manages global network security, DDoS protection at the infrastructure level, and maintains compliance certifications such as SOC, PCI DSS, HIPAA, and FedRAMP. The physical security of AWS data centers is highly restricted and access requires legitimate business need."],
    ["s3","lesson","Customer Responsibilities Security IN the Cloud","Customers are responsible for securing everything they deploy within AWS. This includes configuring IAM users, groups, and roles with least-privilege permissions, encrypting data at rest and in transit, managing operating system patches for EC2 instances, configuring security group rules and network ACLs, implementing application-level security controls, and managing customer-managed encryption keys via KMS or CloudHSM. Customers must also manage their own backups, perform vulnerability assessments, and ensure compliance with industry regulations. AWS provides tools like AWS Config, GuardDuty, Security Hub, and Inspector to help customers meet their security obligations. The key principle is that the more you rely on managed services such as Lambda and RDS, the less operational security burden you carry."],
    ["s4","lesson","Applying the Model to Different Services","The division of responsibility varies by service type. For EC2 in the IaaS model, AWS secures the physical host and hypervisor, while you manage the guest OS, applications, and security groups. For RDS in the PaaS model, AWS manages the database software and OS patching, but you manage database user permissions, schema design, and data encryption. For Lambda in the serverless model, AWS manages the runtime environment, execution role updates, and base OS, you only provide the function code and configure triggers. For S3, AWS manages the infrastructure and durability at 99.999999999 percent, while you configure bucket policies, block public access, enable versioning, and set encryption. Understanding these boundaries helps you allocate security resources effectively."],
    ["s5","quiz","Which is the customer responsibility under the Shared Responsibility Model?","Patching the hypervisor,Physical data center security,Configuring security groups,Replacing failed hardware",2,"Customers are responsible for configuring security groups which act as virtual firewalls to control inbound and outbound traffic to their EC2 instances."],
    ["s6","exercise","Map Responsibilities Matrix","Create a responsibility matrix for EC2 and RDS services. List 5 responsibilities for AWS and 5 for the customer for each service, clearly showing how the boundary shifts between IaaS and PaaS service models in cloud computing."]
  ]],
]
