import { htmlChapters } from "./html-curriculum";
import { cssChapters } from "./css-curriculum";
import { jsChapters } from "./js-curriculum";
import { pythonTrack } from "./python-curriculum";
import { typescriptTrack } from "./typescript-curriculum";
import { cTrack } from "./c-curriculum";
import { cppTrack } from "./cpp-curriculum";
import { javaTrack } from "./java-curriculum";
import { csharpTrack } from "./csharp-curriculum";
import { w3cssTrack } from "./w3css-curriculum";
import { colorsTrack } from "./colors-curriculum";
import { phpTrack } from "./php-curriculum";
import { htmldomTrack } from "./htmldom-curriculum";
import { bootstrap3Track } from "./bootstrap3-curriculum";
import { bootstrap4Track } from "./bootstrap4-curriculum";
import { bootstrap5Track } from "./bootstrap5-curriculum";
import { sqlTrack } from "./sql-curriculum";
import { mysqlTrack } from "./mysql-curriculum";
import { angularTrack } from "./angular-curriculum";
import { vueTrack } from "./vue-curriculum";
import { reactTrack } from "./react-curriculum";
import { kotlinTrack } from "./kotlin-curriculum";
import { postgresqlTrack } from "./postgresql-curriculum";
import { jqueryTrack } from "./jquery-curriculum";
import { numpyTrack } from "./numpy-curriculum";
import { pandasTrack } from "./pandas-curriculum";
import { djangoTrack } from "./django-curriculum";
import { rTrack } from "./r-curriculum";
import { goTrack } from "./go-curriculum";
import { swiftTrack } from "./swift-curriculum";
import { bashTrack } from "./bash-curriculum";
import { scipyTrack } from "./scipy-curriculum";
import { mongodbTrack } from "./mongodb-curriculum";
import { excelTrack } from "./excel-curriculum";
import { dsaTrack } from "./dsa-curriculum";
import { xmlTrack } from "./xml-curriculum";
import { jsonTrack } from "./json-curriculum";
import { nodejsTrack } from "./nodejs-curriculum";
import { aspTrack } from "./asp-curriculum";
import { cybersecurityTrack } from "./cybersecurity-curriculum";
import { awsTrack } from "./aws-curriculum";
import { machinelearningTrack } from "./machinelearning-curriculum";
import { statisticTrack } from "./statistic-curriculum";
import { rwdTrack } from "./rwd-curriculum";
import { ajaxTrack } from "./ajax-curriculum";
import { rustTrack } from "./rust-curriculum";
import { matplotlibTrack } from "./matplotlib-curriculum";
import { utf8Track } from "./utf8-curriculum";
import { piTrack } from "./pi-curriculum";
import { aiTrack } from "./ai-curriculum";
import { genaiTrack } from "./genai-curriculum";
import { introProgrammingTrack } from "./programming-intro-curriculum";
import { accessibilityTrack } from "./accessibility-curriculum";
import { htmlcssIntroTrack } from "./htmlcss-intro-curriculum";
import { codegameTrack } from "./codegame-curriculum";
import { googleSheetsTrack } from "./google-sheets-curriculum";
import { typingSpeedTrack } from "./typing-speed-curriculum";
import { svgTrack } from "./svg-curriculum";
import { iconsTrack } from "./icons-curriculum";
import { canvasTrack } from "./canvas-curriculum";
import { emojiTrack } from "./emoji-curriculum";
import type { Track, TrackId, Chapter } from "./types";
import { trackRelationships } from "@/lib/learning-taxonomy";
export const tracks: Track[] = [
  {
    id: "html",
    title: "HTML",
    titleBn: "এইচটিএমএল",
    tagline: "Builds structure of every website.",
    taglineBn: "প্রতিটি ওয়েবসাইটের কাঠামো তৈরি করে।",
    icon: "https://img.icons8.com/color/144/html-5--v1.png",
    colorVar: "html",
    totalChapters: htmlChapters.length,
    estimatedHours: Math.round(htmlChapters.reduce((sum, c) => sum + c.estimatedMinutes, 0) / 60),
    chapters: htmlChapters,
    brandColor: "#E34F26",
    glowColor: "rgba(227, 79, 38, 0.4)",
  },
  {
    id: "css",
    title: "CSS",
    titleBn: "সিএসএস",
    tagline: "Make websites beautiful and responsive.",
    taglineBn: "ওয়েবসাইটকে সুন্দর এবং প্রতিক্রিয়াশীল করুন।",
    icon: "https://img.icons8.com/color/144/css3.png",
    colorVar: "css",
    totalChapters: cssChapters.length,
    estimatedHours: Math.round(cssChapters.reduce((sum, c) => sum + c.estimatedMinutes, 0) / 60),
    chapters: cssChapters,
    brandColor: "#1572B6",
    glowColor: "rgba(21, 114, 182, 0.4)",
  },
  {
    id: "javascript",
    title: "JavaScript",
    titleBn: "জাভাস্ক্রিপ্ট",
    tagline: "Add interactivity and bring sites to life.",
    taglineBn: "ইন্টারঅ্যাক্টিভিটি যোগ করুন এবং সাইটগুলোকে জীবন্ত করুন।",
    icon: "https://img.icons8.com/color/144/javascript--v1.png",
    colorVar: "javascript",
    totalChapters: jsChapters.length,
    estimatedHours: Math.round(jsChapters.reduce((sum, c) => sum + c.estimatedMinutes, 0) / 60),
    chapters: jsChapters,
    brandColor: "#F7DF1E",
    glowColor: "rgba(247, 223, 30, 0.4)",
  },
  {
    id: "python",
    title: "Python",
    titleBn: "পাইথন",
    tagline: "From scripts to systems — world's most versatile language",
    taglineBn: "স্ক্রিপ্ট থেকে সিস্টেম — বিশ্বের সবচেয়ে বহুমুখী ভাষা",
    icon: "https://img.icons8.com/color/144/python--v1.png",
    colorVar: "python",
    totalChapters: pythonTrack.totalChapters,
    estimatedHours: pythonTrack.estimatedHours,
    chapters: pythonTrack.chapters,
    brandColor: "#F7DF1E",
    glowColor: "#3776AB",
  },
  {
    id: "typescript",
    title: "TypeScript",
    titleBn: "টাইপস্ক্রিপ্ট",
    tagline: "JavaScript, but with superpowers",
    taglineBn: "জাভাস্ক্রিপ্ট, কিন্তু সুপারপাওয়ার্স সহ",
    icon: "https://img.icons8.com/color/144/typescript--v1.png",
    colorVar: "typescript",
    totalChapters: typescriptTrack.totalChapters,
    estimatedHours: typescriptTrack.estimatedHours,
    chapters: typescriptTrack.chapters,
    brandColor: "#3178C6",
    glowColor: "#3178C6",
  },
  {
    id: "c",
    title: "C Programming",
    titleBn: "C প্রোগ্রামিং",
    tagline: "The language that built the modern world",
    taglineBn: "আধুনিক বিশ্ব যে ভাষায় তৈরি",
    icon: "https://img.icons8.com/color/144/c-programming.png",
    colorVar: "c",
    totalChapters: cTrack.totalChapters,
    estimatedHours: cTrack.estimatedHours,
    chapters: cTrack.chapters,
    brandColor: "#A8B9CC",
    glowColor: "#A8B9CC",
  },
  {
    id: "cpp",
    title: "C++ Programming",
    titleBn: "C++ প্রোগ্রামিং",
    tagline: "Zero-cost abstractions. Maximum power.",
    taglineBn: "শূন্য-খরচ বিমূর্ততা। সর্বোচ্চ শক্তি।",
    icon: "https://img.icons8.com/?size=96&id=40669&format=png",
    colorVar: "cpp",
    totalChapters: cppTrack.totalChapters,
    estimatedHours: cppTrack.estimatedHours,
    chapters: cppTrack.chapters,
    brandColor: "#00599C",
    glowColor: "#00599C",
  },
  {
    id: "java",
    title: "Java",
    titleBn: "জাভা",
    tagline: "Write once, run anywhere — the enterprise standard",
    taglineBn: "একবার লিখুন, সব জায়গায় চালান",
    icon: "https://img.icons8.com/?size=160&id=mQ01rhdaQzyT&format=png",
    colorVar: "java",
    totalChapters: javaTrack.totalChapters,
    estimatedHours: javaTrack.estimatedHours,
    chapters: javaTrack.chapters,
    brandColor: "#ED8B00",
    glowColor: "#ED8B00",
  },
  {
    id: "csharp",
    title: "C#",
    titleBn: "সি#",
    tagline: "Elegant, powerful, and backed by .NET",
    taglineBn: "সুন্দর, শক্তিশালী, .NET দ্বারা সমর্থিত",
    icon: "https://img.icons8.com/color/144/c-sharp-logo.png",
    colorVar: "csharp",
    totalChapters: csharpTrack.totalChapters,
    estimatedHours: csharpTrack.estimatedHours,
    chapters: csharpTrack.chapters,
    brandColor: "#9B4993",
    glowColor: "rgba(155, 73, 147, 0.4)",
  },
  {
    id: "w3css",
    title: "W3.CSS",
    titleBn: "W3.CSS",
    tagline: "Style anything. No JavaScript needed.",
    taglineBn: "যেকোনো কিছুতে স্টাইল করুন।",
    icon: "https://img.icons8.com/?size=160&id=7m3rDKCASMFx&format=png",
    colorVar: "w3css",
    totalChapters: w3cssTrack.totalChapters,
    estimatedHours: w3cssTrack.estimatedHours,
    chapters: w3cssTrack.chapters,
    brandColor: "#04AA6D",
    glowColor: "rgba(4, 170, 109, 0.4)",
  },
  {
    id: "colors",
    title: "Web Colors",
    titleBn: "ওয়েব রঙ",
    tagline: "From hex codes to harmony — master color for the web",
    taglineBn: "হেক্স থেকে হারমনি — ওয়েব রঙ মাস্টার করুন",
    icon: "https://img.icons8.com/color/144/color-palette.png",
    colorVar: "colors",
    totalChapters: colorsTrack.totalChapters,
    estimatedHours: colorsTrack.estimatedHours,
    chapters: colorsTrack.chapters,
    brandColor: "#E91E63",
    glowColor: "rgba(233, 30, 99, 0.4)",
  },
  {
    id: "php",
    title: phpTrack.title,
    titleBn: phpTrack.titleBn,
    tagline: phpTrack.tagline,
    taglineBn: phpTrack.taglineBn,
    icon: "https://img.icons8.com/?size=160&id=YrKoPXb4jv9l&format=png",
    colorVar: phpTrack.colorVar,
    totalChapters: phpTrack.totalChapters,
    estimatedHours: phpTrack.estimatedHours,
    chapters: phpTrack.chapters,
    brandColor: phpTrack.brandColor,
    glowColor: phpTrack.glowColor,
  },
  {
    id: "htmldom",
    title: htmldomTrack.title,
    titleBn: htmldomTrack.titleBn,
    tagline: htmldomTrack.tagline,
    taglineBn: htmldomTrack.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=ITAVJ2SvdgZx&format=png",
    colorVar: htmldomTrack.colorVar,
    totalChapters: htmldomTrack.totalChapters,
    estimatedHours: htmldomTrack.estimatedHours,
    chapters: htmldomTrack.chapters,
    brandColor: htmldomTrack.brandColor,
    glowColor: htmldomTrack.glowColor,
  },
  {
    id: bootstrap3Track.id,
    title: bootstrap3Track.title,
    titleBn: bootstrap3Track.titleBn,
    tagline: bootstrap3Track.tagline,
    taglineBn: bootstrap3Track.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=EzPCiQUqWWEa&format=png",
    colorVar: bootstrap3Track.colorVar,
    totalChapters: bootstrap3Track.totalChapters,
    estimatedHours: bootstrap3Track.estimatedHours,
    chapters: bootstrap3Track.chapters,
    brandColor: bootstrap3Track.brandColor,
    glowColor: bootstrap3Track.glowColor,
  },
  {
    id: bootstrap4Track.id,
    title: bootstrap4Track.title,
    titleBn: bootstrap4Track.titleBn,
    tagline: bootstrap4Track.tagline,
    taglineBn: bootstrap4Track.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=EzPCiQUqWWEa&format=png",
    colorVar: bootstrap4Track.colorVar,
    totalChapters: bootstrap4Track.totalChapters,
    estimatedHours: bootstrap4Track.estimatedHours,
    chapters: bootstrap4Track.chapters,
    brandColor: bootstrap4Track.brandColor,
    glowColor: bootstrap4Track.glowColor,
  },
  {
    id: bootstrap5Track.id,
    title: bootstrap5Track.title,
    titleBn: bootstrap5Track.titleBn,
    tagline: bootstrap5Track.tagline,
    taglineBn: bootstrap5Track.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=EzPCiQUqWWEa&format=png",
    colorVar: bootstrap5Track.colorVar,
    totalChapters: bootstrap5Track.totalChapters,
    estimatedHours: bootstrap5Track.estimatedHours,
    chapters: bootstrap5Track.chapters,
    brandColor: bootstrap5Track.brandColor,
    glowColor: bootstrap5Track.glowColor,
  },
  {
    id: sqlTrack.id,
    title: sqlTrack.title,
    titleBn: sqlTrack.titleBn,
    tagline: sqlTrack.tagline,
    taglineBn: sqlTrack.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=J6KcaRLsTgpZ&format=png",
    colorVar: sqlTrack.colorVar,
    totalChapters: sqlTrack.totalChapters,
    estimatedHours: sqlTrack.estimatedHours,
    chapters: sqlTrack.chapters,
    brandColor: sqlTrack.brandColor,
    glowColor: sqlTrack.glowColor,
  },
  {
    id: mysqlTrack.id,
    title: mysqlTrack.title,
    titleBn: mysqlTrack.titleBn,
    tagline: mysqlTrack.tagline,
    taglineBn: mysqlTrack.taglineBn,
    icon: "https://img.icons8.com/?size=160&id=QeIg9siFKGgp&format=png",
    colorVar: mysqlTrack.colorVar,
    totalChapters: mysqlTrack.totalChapters,
    estimatedHours: mysqlTrack.estimatedHours,
    chapters: mysqlTrack.chapters,
    brandColor: mysqlTrack.brandColor,
    glowColor: mysqlTrack.glowColor,
  },
  {
    id: angularTrack.id,
    title: angularTrack.title,
    titleBn: angularTrack.titleBn,
    tagline: angularTrack.tagline,
    taglineBn: angularTrack.taglineBn,
    icon: "https://img.icons8.com/?size=160&id=6SWtW8hxZWSo&format=png",
    colorVar: angularTrack.colorVar,
    totalChapters: angularTrack.totalChapters,
    estimatedHours: angularTrack.estimatedHours,
    chapters: angularTrack.chapters,
    brandColor: angularTrack.brandColor,
    glowColor: angularTrack.glowColor,
  },
  {
    id: vueTrack.id,
    title: vueTrack.title,
    titleBn: vueTrack.titleBn,
    tagline: vueTrack.tagline,
    taglineBn: vueTrack.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=rY6agKizO9eb&format=png",
    colorVar: vueTrack.colorVar,
    totalChapters: vueTrack.totalChapters,
    estimatedHours: vueTrack.estimatedHours,
    chapters: vueTrack.chapters,
    brandColor: vueTrack.brandColor,
    glowColor: vueTrack.glowColor,
  },
{
    id: reactTrack.id,
    title: reactTrack.title,
    titleBn: reactTrack.titleBn,
    tagline: reactTrack.tagline,
    taglineBn: reactTrack.taglineBn,
    icon: "https://img.icons8.com/?size=128&id=p57acgidi9bj&format=png",
    colorVar: reactTrack.colorVar,
    totalChapters: reactTrack.totalChapters,
    estimatedHours: reactTrack.estimatedHours,
    chapters: reactTrack.chapters,
    brandColor: reactTrack.brandColor,
    glowColor: reactTrack.glowColor,
  },
{
    id: kotlinTrack.id,
    title: kotlinTrack.title,
    titleBn: kotlinTrack.titleBn,
    tagline: kotlinTrack.tagline,
    taglineBn: kotlinTrack.taglineBn,
    icon: kotlinTrack.icon,
    colorVar: kotlinTrack.colorVar,
    totalChapters: kotlinTrack.totalChapters,
    estimatedHours: kotlinTrack.estimatedHours,
    chapters: kotlinTrack.chapters,
    brandColor: kotlinTrack.brandColor,
    glowColor: kotlinTrack.glowColor,
  },
  {
    id: postgresqlTrack.id,
    title: postgresqlTrack.title,
    titleBn: postgresqlTrack.titleBn,
    tagline: postgresqlTrack.tagline,
    taglineBn: postgresqlTrack.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=38561&format=png",
    colorVar: postgresqlTrack.colorVar,
    totalChapters: postgresqlTrack.totalChapters,
    estimatedHours: postgresqlTrack.estimatedHours,
    chapters: postgresqlTrack.chapters,
    brandColor: postgresqlTrack.brandColor,
    glowColor: postgresqlTrack.glowColor,
  },
  {
    id: jqueryTrack.id,
    title: jqueryTrack.title,
    titleBn: jqueryTrack.titleBn,
    tagline: jqueryTrack.tagline,
    taglineBn: jqueryTrack.taglineBn,
    icon: "https://img.icons8.com/?size=160&id=HKNzD81eiiSc&format=png",
    colorVar: jqueryTrack.colorVar,
    totalChapters: jqueryTrack.totalChapters,
    estimatedHours: jqueryTrack.estimatedHours,
    chapters: jqueryTrack.chapters,
    brandColor: jqueryTrack.brandColor,
    glowColor: jqueryTrack.glowColor,
  },
  {
    id: numpyTrack.id,
    title: numpyTrack.title,
    titleBn: numpyTrack.titleBn,
    tagline: numpyTrack.tagline,
    taglineBn: numpyTrack.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=aR9CXyMagKIS&format=png",
    colorVar: numpyTrack.colorVar,
    totalChapters: numpyTrack.totalChapters,
    estimatedHours: numpyTrack.estimatedHours,
    chapters: numpyTrack.chapters,
    brandColor: numpyTrack.brandColor,
    glowColor: numpyTrack.glowColor,
  },
  {
    id: pandasTrack.id,
    title: pandasTrack.title,
    titleBn: pandasTrack.titleBn,
    tagline: pandasTrack.tagline,
    taglineBn: pandasTrack.taglineBn,
    icon: "https://img.icons8.com/?size=96&id=xSkewUSqtErH&format=png",
    colorVar: pandasTrack.colorVar,
    totalChapters: pandasTrack.totalChapters,
    estimatedHours: pandasTrack.estimatedHours,
    chapters: pandasTrack.chapters,
    brandColor: pandasTrack.brandColor,
    glowColor: pandasTrack.glowColor,
  },
  {
    id: djangoTrack.id,
    title: djangoTrack.title,
    titleBn: djangoTrack.titleBn,
    tagline: djangoTrack.tagline,
    taglineBn: djangoTrack.taglineBn,
    icon: "https://img.icons8.com/?size=160&id=9YYvIDj9TYP5&format=png",
    colorVar: djangoTrack.colorVar,
    totalChapters: djangoTrack.totalChapters,
    estimatedHours: djangoTrack.estimatedHours,
    chapters: djangoTrack.chapters,
    brandColor: djangoTrack.brandColor,
    glowColor: djangoTrack.glowColor,
  },
  {
    id: rTrack.id,
    title: rTrack.title,
    titleBn: rTrack.titleBn,
    tagline: rTrack.tagline,
    taglineBn: rTrack.taglineBn,
    icon: rTrack.icon,
    colorVar: rTrack.colorVar,
    totalChapters: rTrack.totalChapters,
    estimatedHours: rTrack.estimatedHours,
    chapters: rTrack.chapters,
    brandColor: rTrack.brandColor,
    glowColor: rTrack.glowColor,
  },
  {
    id: goTrack.id,
    title: goTrack.title,
    titleBn: goTrack.titleBn,
    tagline: goTrack.tagline,
    taglineBn: goTrack.taglineBn,
    icon: goTrack.icon,
    colorVar: goTrack.colorVar,
    totalChapters: goTrack.totalChapters,
    estimatedHours: goTrack.estimatedHours,
    chapters: goTrack.chapters,
    brandColor: goTrack.brandColor,
    glowColor: goTrack.glowColor,
  },
  {
    id: swiftTrack.id,
    title: swiftTrack.title,
    titleBn: swiftTrack.titleBn,
    tagline: swiftTrack.tagline,
    taglineBn: swiftTrack.taglineBn,
    icon: swiftTrack.icon,
    colorVar: swiftTrack.colorVar,
    totalChapters: swiftTrack.totalChapters,
    estimatedHours: swiftTrack.estimatedHours,
    chapters: swiftTrack.chapters,
    brandColor: swiftTrack.brandColor,
    glowColor: swiftTrack.glowColor,
  },
  {
    id: scipyTrack.id,
    title: scipyTrack.title,
    titleBn: scipyTrack.titleBn,
    tagline: scipyTrack.tagline,
    taglineBn: scipyTrack.taglineBn,
    icon: scipyTrack.icon,
    colorVar: scipyTrack.colorVar,
    totalChapters: scipyTrack.totalChapters,
    estimatedHours: scipyTrack.estimatedHours,
    chapters: scipyTrack.chapters,
    brandColor: scipyTrack.brandColor,
    glowColor: scipyTrack.glowColor,
  },
  {
    id: mongodbTrack.id,
    title: mongodbTrack.title,
    titleBn: mongodbTrack.titleBn,
    tagline: mongodbTrack.tagline,
    taglineBn: mongodbTrack.taglineBn,
    icon: mongodbTrack.icon,
    colorVar: mongodbTrack.colorVar,
    totalChapters: mongodbTrack.totalChapters,
    estimatedHours: mongodbTrack.estimatedHours,
    chapters: mongodbTrack.chapters,
    brandColor: mongodbTrack.brandColor,
    glowColor: mongodbTrack.glowColor,
  },
  {
    id: excelTrack.id,
    title: excelTrack.title,
    titleBn: excelTrack.titleBn,
    tagline: excelTrack.tagline,
    taglineBn: excelTrack.taglineBn,
    icon: excelTrack.icon,
    colorVar: excelTrack.colorVar,
    totalChapters: excelTrack.totalChapters,
    estimatedHours: excelTrack.estimatedHours,
    chapters: excelTrack.chapters,
    brandColor: excelTrack.brandColor,
    glowColor: excelTrack.glowColor,
  },
  {
    id: dsaTrack.id,
    title: dsaTrack.title,
    titleBn: dsaTrack.titleBn,
    tagline: dsaTrack.tagline,
    taglineBn: dsaTrack.taglineBn,
    icon: dsaTrack.icon,
    colorVar: dsaTrack.colorVar,
    totalChapters: dsaTrack.totalChapters,
    estimatedHours: dsaTrack.estimatedHours,
    chapters: dsaTrack.chapters,
    brandColor: dsaTrack.brandColor,
    glowColor: dsaTrack.glowColor,
  },
  {
    id: bashTrack.id,
    title: bashTrack.title,
    titleBn: bashTrack.titleBn,
    tagline: bashTrack.tagline,
    taglineBn: bashTrack.taglineBn,
    icon: bashTrack.icon,
    colorVar: bashTrack.colorVar,
    totalChapters: bashTrack.totalChapters,
    estimatedHours: bashTrack.estimatedHours,
    chapters: bashTrack.chapters,
    brandColor: bashTrack.brandColor,
    glowColor: bashTrack.glowColor,
  },
  {
    id: xmlTrack.id,
    title: xmlTrack.title,
    titleBn: xmlTrack.titleBn,
    tagline: xmlTrack.tagline,
    taglineBn: xmlTrack.taglineBn,
    icon: xmlTrack.icon,
    colorVar: xmlTrack.colorVar,
    totalChapters: xmlTrack.totalChapters,
    estimatedHours: xmlTrack.estimatedHours,
    chapters: xmlTrack.chapters,
    brandColor: xmlTrack.brandColor,
    glowColor: xmlTrack.glowColor,
  },
  {
    id: jsonTrack.id,
    title: jsonTrack.title,
    titleBn: jsonTrack.titleBn,
    tagline: jsonTrack.tagline,
    taglineBn: jsonTrack.taglineBn,
    icon: jsonTrack.icon,
    colorVar: jsonTrack.colorVar,
    totalChapters: jsonTrack.totalChapters,
    estimatedHours: jsonTrack.estimatedHours,
    chapters: jsonTrack.chapters,
    brandColor: jsonTrack.brandColor,
    glowColor: jsonTrack.glowColor,
  },
  {
    id: nodejsTrack.id,
    title: nodejsTrack.title,
    titleBn: nodejsTrack.titleBn,
    tagline: nodejsTrack.tagline,
    taglineBn: nodejsTrack.taglineBn,
    icon: nodejsTrack.icon,
    colorVar: nodejsTrack.colorVar,
    totalChapters: nodejsTrack.totalChapters,
    estimatedHours: nodejsTrack.estimatedHours,
    chapters: nodejsTrack.chapters,
    brandColor: nodejsTrack.brandColor,
    glowColor: nodejsTrack.glowColor,
  },
  {
    id: aspTrack.id,
    title: aspTrack.title,
    titleBn: aspTrack.titleBn,
    tagline: aspTrack.tagline,
    taglineBn: aspTrack.taglineBn,
    icon: aspTrack.icon,
    colorVar: aspTrack.colorVar,
    totalChapters: aspTrack.totalChapters,
    estimatedHours: aspTrack.estimatedHours,
    chapters: aspTrack.chapters,
    brandColor: aspTrack.brandColor,
    glowColor: aspTrack.glowColor,
  },
  {
    id: cybersecurityTrack.id,
    title: cybersecurityTrack.title,
    titleBn: cybersecurityTrack.titleBn,
    tagline: cybersecurityTrack.tagline,
    taglineBn: cybersecurityTrack.taglineBn,
    icon: cybersecurityTrack.icon,
    colorVar: cybersecurityTrack.colorVar,
    totalChapters: cybersecurityTrack.totalChapters,
    estimatedHours: cybersecurityTrack.estimatedHours,
    chapters: cybersecurityTrack.chapters,
    brandColor: cybersecurityTrack.brandColor,
    glowColor: cybersecurityTrack.glowColor,
  },
  {
    id: awsTrack.id,
    title: awsTrack.title,
    titleBn: awsTrack.titleBn,
    tagline: awsTrack.tagline,
    taglineBn: awsTrack.taglineBn,
    icon: awsTrack.icon,
    colorVar: awsTrack.colorVar,
    totalChapters: awsTrack.totalChapters,
    estimatedHours: awsTrack.estimatedHours,
    chapters: awsTrack.chapters,
    brandColor: awsTrack.brandColor,
    glowColor: awsTrack.glowColor,
  },
  {
    id: machinelearningTrack.id,
    title: machinelearningTrack.title,
    titleBn: machinelearningTrack.titleBn,
    tagline: machinelearningTrack.tagline,
    taglineBn: machinelearningTrack.taglineBn,
    icon: machinelearningTrack.icon,
    colorVar: machinelearningTrack.colorVar,
    totalChapters: machinelearningTrack.totalChapters,
    estimatedHours: machinelearningTrack.estimatedHours,
    chapters: machinelearningTrack.chapters,
    brandColor: machinelearningTrack.brandColor,
    glowColor: machinelearningTrack.glowColor,
  },
  {
    id: statisticTrack.id,
    title: statisticTrack.title,
    titleBn: statisticTrack.titleBn,
    tagline: statisticTrack.tagline,
    taglineBn: statisticTrack.taglineBn,
    icon: statisticTrack.icon,
    colorVar: statisticTrack.colorVar,
    totalChapters: statisticTrack.totalChapters,
    estimatedHours: statisticTrack.estimatedHours,
    chapters: statisticTrack.chapters,
    brandColor: statisticTrack.brandColor,
    glowColor: statisticTrack.glowColor,
  },
  {
    id: rwdTrack.id,
    title: rwdTrack.title,
    titleBn: rwdTrack.titleBn,
    tagline: rwdTrack.tagline,
    taglineBn: rwdTrack.taglineBn,
    icon: rwdTrack.icon,
    colorVar: rwdTrack.colorVar,
    totalChapters: rwdTrack.totalChapters,
    estimatedHours: rwdTrack.estimatedHours,
    chapters: rwdTrack.chapters,
    brandColor: rwdTrack.brandColor,
    glowColor: rwdTrack.glowColor,
  },
  {
    id: ajaxTrack.id,
    title: ajaxTrack.title,
    titleBn: ajaxTrack.titleBn,
    tagline: ajaxTrack.tagline,
    taglineBn: ajaxTrack.taglineBn,
    icon: ajaxTrack.icon,
    colorVar: ajaxTrack.colorVar,
    totalChapters: ajaxTrack.totalChapters,
    estimatedHours: ajaxTrack.estimatedHours,
    chapters: ajaxTrack.chapters,
    brandColor: ajaxTrack.brandColor,
    glowColor: ajaxTrack.glowColor,
  },
  {
    id: rustTrack.id,
    title: rustTrack.title,
    titleBn: rustTrack.titleBn,
    tagline: rustTrack.tagline,
    taglineBn: rustTrack.taglineBn,
    icon: rustTrack.icon,
    colorVar: rustTrack.colorVar,
    totalChapters: rustTrack.totalChapters,
    estimatedHours: rustTrack.estimatedHours,
    chapters: rustTrack.chapters,
    brandColor: rustTrack.brandColor,
    glowColor: rustTrack.glowColor,
  },
  {
    id: matplotlibTrack.id,
    title: matplotlibTrack.title,
    titleBn: matplotlibTrack.titleBn,
    tagline: matplotlibTrack.tagline,
    taglineBn: matplotlibTrack.taglineBn,
    icon: matplotlibTrack.icon,
    colorVar: matplotlibTrack.colorVar,
    totalChapters: matplotlibTrack.totalChapters,
    estimatedHours: matplotlibTrack.estimatedHours,
    chapters: matplotlibTrack.chapters,
    brandColor: matplotlibTrack.brandColor,
    glowColor: matplotlibTrack.glowColor,
  },
  {
    id: utf8Track.id,
    title: utf8Track.title,
    titleBn: utf8Track.titleBn,
    tagline: utf8Track.tagline,
    taglineBn: utf8Track.taglineBn,
    icon: utf8Track.icon,
    colorVar: utf8Track.colorVar,
    totalChapters: utf8Track.totalChapters,
    estimatedHours: utf8Track.estimatedHours,
    chapters: utf8Track.chapters,
    brandColor: utf8Track.brandColor,
    glowColor: utf8Track.glowColor,
  },
  {
    id: piTrack.id,
    title: piTrack.title,
    titleBn: piTrack.titleBn,
    tagline: piTrack.tagline,
    taglineBn: piTrack.taglineBn,
    icon: piTrack.icon,
    colorVar: piTrack.colorVar,
    totalChapters: piTrack.totalChapters,
    estimatedHours: piTrack.estimatedHours,
    chapters: piTrack.chapters,
    brandColor: piTrack.brandColor,
    glowColor: piTrack.glowColor,
  },
  {
    id: aiTrack.id,
    title: aiTrack.title,
    titleBn: aiTrack.titleBn,
    tagline: aiTrack.tagline,
    taglineBn: aiTrack.taglineBn,
    icon: aiTrack.icon,
    colorVar: aiTrack.colorVar,
    totalChapters: aiTrack.totalChapters,
    estimatedHours: aiTrack.estimatedHours,
    chapters: aiTrack.chapters,
    brandColor: aiTrack.brandColor,
    glowColor: aiTrack.glowColor,
  },
  {
    id: genaiTrack.id,
    title: genaiTrack.title,
    titleBn: genaiTrack.titleBn,
    tagline: genaiTrack.tagline,
    taglineBn: genaiTrack.taglineBn,
    icon: genaiTrack.icon,
    colorVar: genaiTrack.colorVar,
    totalChapters: genaiTrack.totalChapters,
    estimatedHours: genaiTrack.estimatedHours,
    chapters: genaiTrack.chapters,
    brandColor: genaiTrack.brandColor,
    glowColor: genaiTrack.glowColor,
  },
  {
    id: introProgrammingTrack.id,
    title: introProgrammingTrack.title,
    titleBn: introProgrammingTrack.titleBn,
    tagline: introProgrammingTrack.tagline,
    taglineBn: introProgrammingTrack.taglineBn,
    icon: introProgrammingTrack.icon,
    colorVar: introProgrammingTrack.colorVar,
    totalChapters: introProgrammingTrack.totalChapters,
    estimatedHours: introProgrammingTrack.estimatedHours,
    chapters: introProgrammingTrack.chapters,
    brandColor: introProgrammingTrack.brandColor,
    glowColor: introProgrammingTrack.glowColor,
  },
  {
    id: accessibilityTrack.id,
    title: accessibilityTrack.title,
    titleBn: accessibilityTrack.titleBn,
    tagline: accessibilityTrack.tagline,
    taglineBn: accessibilityTrack.taglineBn,
    icon: accessibilityTrack.icon,
    colorVar: accessibilityTrack.colorVar,
    totalChapters: accessibilityTrack.totalChapters,
    estimatedHours: accessibilityTrack.estimatedHours,
    chapters: accessibilityTrack.chapters,
    brandColor: accessibilityTrack.brandColor,
    glowColor: accessibilityTrack.glowColor,
  },
  {
    id: htmlcssIntroTrack.id,
    title: htmlcssIntroTrack.title,
    titleBn: htmlcssIntroTrack.titleBn,
    tagline: htmlcssIntroTrack.tagline,
    taglineBn: htmlcssIntroTrack.taglineBn,
    icon: htmlcssIntroTrack.icon,
    colorVar: htmlcssIntroTrack.colorVar,
    totalChapters: htmlcssIntroTrack.totalChapters,
    estimatedHours: htmlcssIntroTrack.estimatedHours,
    chapters: htmlcssIntroTrack.chapters,
    brandColor: htmlcssIntroTrack.brandColor,
    glowColor: htmlcssIntroTrack.glowColor,
  },
  {
    id: codegameTrack.id,
    title: codegameTrack.title,
    titleBn: codegameTrack.titleBn,
    tagline: codegameTrack.tagline,
    taglineBn: codegameTrack.taglineBn,
    icon: codegameTrack.icon,
    colorVar: codegameTrack.colorVar,
    totalChapters: codegameTrack.totalChapters,
    estimatedHours: codegameTrack.estimatedHours,
    chapters: codegameTrack.chapters,
    brandColor: codegameTrack.brandColor,
    glowColor: codegameTrack.glowColor,
  },
  {
    id: googleSheetsTrack.id,
    title: googleSheetsTrack.title,
    titleBn: googleSheetsTrack.titleBn,
    tagline: googleSheetsTrack.tagline,
    taglineBn: googleSheetsTrack.taglineBn,
    icon: googleSheetsTrack.icon,
    colorVar: googleSheetsTrack.colorVar,
    totalChapters: googleSheetsTrack.totalChapters,
    estimatedHours: googleSheetsTrack.estimatedHours,
    chapters: googleSheetsTrack.chapters,
    brandColor: googleSheetsTrack.brandColor,
    glowColor: googleSheetsTrack.glowColor,
  },
  {
    id: typingSpeedTrack.id,
    title: typingSpeedTrack.title,
    titleBn: typingSpeedTrack.titleBn,
    tagline: typingSpeedTrack.tagline,
    taglineBn: typingSpeedTrack.taglineBn,
    icon: typingSpeedTrack.icon,
    colorVar: typingSpeedTrack.colorVar,
    totalChapters: typingSpeedTrack.totalChapters,
    estimatedHours: typingSpeedTrack.estimatedHours,
    chapters: typingSpeedTrack.chapters,
    brandColor: typingSpeedTrack.brandColor,
    glowColor: typingSpeedTrack.glowColor,
  },
  {
    id: svgTrack.id,
    title: svgTrack.title,
    titleBn: svgTrack.titleBn,
    tagline: svgTrack.tagline,
    taglineBn: svgTrack.taglineBn,
    icon: svgTrack.icon,
    colorVar: svgTrack.colorVar,
    totalChapters: svgTrack.totalChapters,
    estimatedHours: svgTrack.estimatedHours,
    chapters: svgTrack.chapters,
    brandColor: svgTrack.brandColor,
    glowColor: svgTrack.glowColor,
  },
  {
    id: iconsTrack.id,
    title: iconsTrack.title,
    titleBn: iconsTrack.titleBn,
    tagline: iconsTrack.tagline,
    taglineBn: iconsTrack.taglineBn,
    icon: iconsTrack.icon,
    colorVar: iconsTrack.colorVar,
    totalChapters: iconsTrack.totalChapters,
    estimatedHours: iconsTrack.estimatedHours,
    chapters: iconsTrack.chapters,
    brandColor: iconsTrack.brandColor,
    glowColor: iconsTrack.glowColor,
  },
  {
    id: canvasTrack.id,
    title: canvasTrack.title,
    titleBn: canvasTrack.titleBn,
    tagline: canvasTrack.tagline,
    taglineBn: canvasTrack.taglineBn,
    icon: canvasTrack.icon,
    colorVar: canvasTrack.colorVar,
    totalChapters: canvasTrack.totalChapters,
    estimatedHours: canvasTrack.estimatedHours,
    chapters: canvasTrack.chapters,
    brandColor: canvasTrack.brandColor,
    glowColor: canvasTrack.glowColor,
  },
  {
    id: emojiTrack.id,
    title: emojiTrack.title,
    titleBn: emojiTrack.titleBn,
    tagline: emojiTrack.tagline,
    taglineBn: emojiTrack.taglineBn,
    icon: emojiTrack.icon,
    colorVar: emojiTrack.colorVar,
    totalChapters: emojiTrack.totalChapters,
    estimatedHours: emojiTrack.estimatedHours,
    chapters: emojiTrack.chapters,
    brandColor: emojiTrack.brandColor,
    glowColor: emojiTrack.glowColor,
  },
];

// Enrich tracks with taxonomy data
export const enrichedTracks: Track[] = tracks.map(track => {
  const rel = trackRelationships[track.id];
  if (!rel) return track;
  return {
    ...track,
    prerequisites: rel.prerequisites,
    relatedTracks: rel.relatedTracks,
    recommendedAfter: rel.recommendedAfter,
    category: rel.category,
    subcategory: rel.subcategory,
    difficulty: rel.difficulty,
  };
});

export const getTrack = (id: TrackId): Track | undefined => enrichedTracks.find((t) => t.id === id);

export const getChapter = (trackId: TrackId, chapterId: string): Chapter | undefined => {
  const track = getTrack(trackId);
  return track?.chapters.find((c) => c.id === chapterId);
};

export const getNextChapter = (trackId: TrackId, chapterId: string): Chapter | undefined => {
  const track = getTrack(trackId);
  if (!track) return undefined;
  const idx = track.chapters.findIndex((c) => c.id === chapterId);
  return idx >= 0 && idx < track.chapters.length - 1 ? track.chapters[idx + 1] : undefined;
};

export const getPrevChapter = (trackId: TrackId, chapterId: string): Chapter | undefined => {
  const track = getTrack(trackId);
  if (!track) return undefined;
  const idx = track.chapters.findIndex((c) => c.id === chapterId);
  return idx > 0 ? track.chapters[idx - 1] : undefined;
};

export * from "./types";
